### PR TITLE
Templating: Prevents crash when $__searchFilter is not a string

### LINKED ISSUE #20525: Variable selector doesn't work with datasources implementing VariableQueryEditor
**What happened**:
Variable selector failed to load:
Screenshot from 2019-11-20 17-04-48

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard, add template variable with type query and one of the datasources implementing its own `VariableQueryEditor` (Splunk, Dynatrace, Stackdriver).

Screenshot from 2019-11-20 17-05-15

**Anything else we need to know?**:
There's an error in console:
```
TypeError: query.indexOf is not a function
    at containsSearchFilter (variable.ts:22)
    at ValueSelectDropdownCtrl (value_select_dropdown.ts:32)
```
This behaviour was introduced by cb0e80e7b92c93336901992ade8e2cd73a8d49c2
This PR assumes `query` is a string, but if datasource implements `VariableQueryEditor` it may be arbitrary object. So basic fix may be like:
```ts
export const containsSearchFilter = (query: string): boolean =>
  query && typeof query === 'string' ? query.indexOf(SEARCH_FILTER_VARIABLE) !== -1 : false;
```

**Environment**:
- Grafana version: Grafana v6.5.0-beta1 (ab9c0da30e)

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #20525

**Special notes for your reviewer**:

### CODE REVIEW

**Review by alexanderzobnin — APPROVED** [review]
Looks good, this fixes a Splunk problem.

**Review by daniellee — APPROVED** [review]
Tested with Stackdriver and Dynatrace which are the other two data sources that implement the new variable query editor and they both worked again with this fix.
