### ISSUE TITLE
Grafana doesn't work on Safari after update to grafana/stable 8.0.1 amd64 [upgradable from: 7.5.7]

### ISSUE THREAD

**Issue by struxoje** [grafana/grafana#35594]
**What happened**:
After upgrade Grafana doesn't work on Safari desktop, Safari mobile, Chrome mobile. Chrome desktop, Brave desktop do work post login page. Upgrade was: grafana/stable 8.0.1 amd64 [upgradable from: 7.5.7]
After logging in I get the following instead of homepage:

If you're seeing this Grafana has failed to load its application files 

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

4. Sometimes restarting grafana-server can help

5. Check if you are using a non-supported browser. For more information, refer to the list of supported browsers.

An unexpected error happened
TypeError: undefined is not an object (evaluating 'this.window.panelsRendered=this.panelsRendered')

Di@http://192.168.1.100:8082/public/build/app.c916c34d6a21e5f99f35.js:3727:1574621
div
ee@http://192.168.1.100:8082/public/build/default~DashboardPage~SoloPanelPage.c916c34d6a21e5f99f35.js:10:14763
div
t@http://192.168.1.100:8082/public/build/vendors~app.c916c34d6a21e5f99f35.js:2:1897377
div
ce@http://192.168.1.100:8082/public/build/default~DashboardPage~SoloPanelPage.c916c34d6a21e5f99f35.js:10:24253
k@http://192.168.1.100:8082/public/build/vendors~app.c916c34d6a21e5f99f35.js:2:70367
div
r@http://192.168.1.100:8082/public/build/DashboardPage.c916c34d6a21e5f99f35.js:95:145924
DraggableCore@http://192.168.1.100:8082/public/build/DashboardPage.c916c34d6a21e5f99f35.js:19:90940
p@http://192.168.1.100:8082/public/build/DashboardPage.c916c34d6a21e5f99f35.js:19:74563
div
ReactGridLayout@http://192.168.1.100:8082/public/build/DashboardPage.c916c34d6a21e5f99f35.js:95:131610
http://192.168.1.100:8082/public/build/DashboardPage.c916c34d6a21e5f99f35.js:500:252409
SizeMeReferenceWrapper@http://192.168.1.100:8082/public/build/DashboardPage.c916c34d6a21e5f99f35.js:19:66913
SizeMeRenderer(Component)@http://192.168.1.100:8082/public/build/DashboardPage.c916c34d6a21e5f99f35.js:19:67345
SizeMe(Component)@http://192.168.1.100:8082/public/build/DashboardPage.c916c34d6a21e5f99f35.js:19:68649
j@http://192.168.1.100:8082/public/build/DashboardPage.c916c34d6a21e5f99f35.js:500:252821
div
div
div
t@http://192.168.1.100:8082/public/build/vendors~app.c916c34d6a21e5f99f35.js:2:706837
h@http://192.168.1.100:8082/public/build/app.c916c34d6a21e5f99f35.js:5438:2411703
div
div
W@http://192.168.1.100:8082/public/build/Dashboar

**What you expected to happen**:
To see logged in homepage
**How to reproduce it (as minimally and precisely as possible)**:
Just running sudo apt update / sudo apt upgrade 
Upgrade was from version 7.5.7 to 8.0.1

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana/stable 8.0.1 amd64 [upgradable from: 7.5.7]
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 21.04
- User OS & Browser: Safari
- Grafana plugins: Standard ones
- Others:

**Comment by struxoje** [comment]
Downgrading back to 7.5.7 fixed the problem: 
sudo apt-get install grafana=7.5.7

**Comment by torkelo** [comment]
Super strange, no similar report. Can you try a v8 on a fresh install?

**Comment by struxoje** [comment]
Unfortunately I cannot do clean install right now

**Comment by torkelo** [comment]
What version of Safari are you using?

**Comment by struxoje** [comment]
Version 14.1 (16611.1.21.161.3)

**Comment by Codelica** [comment]
Seeing this as well after updating Grafana to 8.0.3 this morning.  Safari 13.0.5 shows the "failed to load application files" screen.  Chrome, Firefox, Brave are all fine.

**Comment by Codelica** [comment]
FWIW I came from 7.5.7 to 8.0.3 via Ubuntu apt-upgrade.  Console error in Safari:

```
[Error] TypeError: t.addEventListener is not a function. (In 't.addEventListener(e,n,r?fe:le)', 't.addEventListener' is undefined)
	de (vendors~app.90f320b382a70cd0232d.js:2:2216404)
	e (vendors~app.90f320b382a70cd0232d.js:2:2216630)
	q1RN (vendors~app.90f320b382a70cd0232d.js:2:2216694)
	o (runtime.90f320b382a70cd0232d.js:1:566)
	8mZN (app.90f320b382a70cd0232d.js:690:379122)
	o (runtime.90f320b382a70cd0232d.js:1:566)
	dK2y (app.90f320b382a70cd0232d.js:4390:1932805)
	o (runtime.90f320b382a70cd0232d.js:1:566)
	aPt1 (app.90f320b382a70cd0232d.js:3305:64444)
	o (runtime.90f320b382a70cd0232d.js:1:566)
	kDLi (app.90f320b382a70cd0232d.js:5124:2146721)
	o (runtime.90f320b382a70cd0232d.js:1:566)
	t8hP (app.90f320b382a70cd0232d.js:5435:2359986)
	o (runtime.90f320b382a70cd0232d.js:1:566)
	ZFWI (app.90f320b382a70cd0232d.js:2811:1416108)
	o (runtime.90f320b382a70cd0232d.js:1:566)
	zl43 (app.90f320b382a70cd0232d.js:5537:2488033)
	o (runtime.90f320b382a70cd0232d.js:1:566)
	r (runtime.90f320b382a70cd0232d.js:1:432)
	t (runtime.90f320b382a70cd0232d.js:1:295)
	Global Code (vendors~app.90f320b382a70cd0232d.js:2)
```

**Comment by leeoniya** [comment]
```
[Error] TypeError: t.addEventListener is not a function. (In 't.addEventListener(e,n,r?fe:le)', 't.addEventListener' is undefined
```

that looks suspiciously like https://github.com/leeoniya/uPlot/blob/master/src/dom.js#L75

the old spec of developer.mozilla.org/en-US/docs/Web/API/MediaQueryList which Safari < 14 uses only has addListener but not addEventListener. [1]

can you try opening a uPlot demo and see if you get a similar error?

e.g. https://leeoniya.github.io/uPlot/demos/area-fill.html

if this is the issue, we should add a simple shim for Safari < 14 in Grafana that aliases the `addEventListener` and `removeEventListener` to the deprecated names.

[1] https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener

**Comment by leeoniya** [comment]
it looks like globally there is 0.57% iOS users with incompatible Safari versions, too few to Safari desktop users to show in this chart https://caniuse.com/mdn-api_mediaquerylistevent_mediaquerylistevent

![image](https://user-images.githubusercontent.com/43234/122621689-e48d5100-d05b-11eb-9720-26830a3f6c00.png)

**Comment by Codelica** [comment]
Yep... I see the same error w/ your github.io link.   Just to be clear this is Safari "desktop" 13.0.5.  -- basically a machine running MacOS Mojave 10.14.6 we use for testing.  

If Grafana 8.x requires Safari 14+ for MacOS/iOS that should probably be noted though, as that is a relatively new release. Like last September on the desktop side.

**Comment by leeoniya** [comment]
yeah, this is a conversation wee need to have internally. AFAIK our end-to-end CI tests for all pull requests run Chrome 86:

![image](https://user-images.githubusercontent.com/43234/122623571-39cc6100-d062-11eb-97f0-cc2548a19dfb.png)

the official party line has general browser names, but not versions that are actually e2e tested: https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers

i can tell you that if you try an old-enough version of any of those browsers, _something_ will certainly break.

for the most part, we have hundreds of engineers and likely hundreds of early-adopters who use pre-release versions of Grafana on a daily basis with a large percentage doing so in Safari, so that's a loose feedback loop for stating general support for it. that being said, we only merged that uPlot update within the last couple days before 8.0.3, so this would have only been caught by someone on a relatively outdated OS or browser running into it (unlikely).

since the fix for this appears pretty straightforward, i expect it'll be riding the next patch release train. as for officially supported versions of browsers the only answer i can give with any confidence right now is "at least chrome 86 and latest version of everything else".

**Comment by thisisobate** [comment]
Confirmed. This is a bug on safari 13.

**Comment by ajimix** [comment]
> Noticed signing out and signing back into Grafana works as expected. Would mark this as a bug right away.

I cannot even login because I get the error directly. So Grafana is unusable for me after 8.0.3 upgrade on Safari 13

> FWIW I came from 7.5.7 to 8.0.3 via Ubuntu apt-upgrade. Console error in Safari:
> 
> ```
> [Error] TypeError: t.addEventListener is not a function. (In 't.addEventListener(e,n,r?fe:le)', 't.addEventListener' is undefined)
> 	de (vendors~app.90f320b382a70cd0232d.js:2:2216404)
> 	e (vendors~app.90f320b382a70cd0232d.js:2:2216630)
> 	q1RN (vendors~app.90f320b382a70cd0232d.js:2:2216694)
> 	o (runtime.90f320b382a70cd0232d.js:1:566)
> 	8mZN (app.90f320b382a70cd0232d.js:690:379122)
> 	o (runtime.90f320b382a70cd0232d.js:1:566)
> 	dK2y (app.90f320b382a70cd0232d.js:4390:1932805)
> 	o (runtime.90f320b382a70cd0232d.js:1:566)
> 	aPt1 (app.90f320b382a70cd0232d.js:3305:64444)
> 	o (runtime.90f320b382a70cd0232d.js:1:566)
> 	kDLi (app.90f320b382a70cd0232d.js:5124:2146721)
> 	o (runtime.90f320b382a70cd0232d.js:1:566)
> 	t8hP (app.90f320b382a70cd0232d.js:5435:2359986)
> 	o (runtime.90f320b382a70cd0232d.js:1:566)
> 	ZFWI (app.90f320b382a70cd0232d.js:2811:1416108)
> 	o (runtime.90f320b382a70cd0232d.js:1:566)
> 	zl43 (app.90f320b382a70cd0232d.js:5537:2488033)
> 	o (runtime.90f320b382a70cd0232d.js:1:566)
> 	r (runtime.90f320b382a70cd0232d.js:1:432)
> 	t (runtime.90f320b382a70cd0232d.js:1:295)
> 	Global Code (vendors~app.90f320b382a70cd0232d.js:2)
> ```

**Comment by torkelo** [comment]
@ajimix can you update Safari?

**Comment by DjoeC** [comment]
Same problem here: Windows 8.1, Firefox 72 (version januari 2020 - not that old) after upgrade to 8.0.3.  Raspberry OS 64bit (Debian).  Downgrade to 7.5.9 restores functionality.

**Comment by thisisobate** [comment]
After many iterations with different matchmedia polyfills, I noticed adding a shim/polyfill doesn't have any effect on the Grafana App. Weird behavior.

**Comment by thisisobate** [comment]
Fixed #36274

**Comment by SaKiEQ** [comment]
I just update to Grafana 8.4.2 and now I can no longer use it with Safari 13.1.2. 
I am aware that this is an older Safari version, but many developers like me stay on older OS X version, where system protection (SIP) can be easily turned off, where certain hardware drivers are wider compatible than on up-to-date system.

The same machine can open Grafana in Chrome or Firefox, but not the default Safari 13. Nothing changed on the Mac end - only the Linux machine hosting Grafana got updated. 

Is there a way to manually override browser version check ? 

(I will toss Grafana before I will give up an stable and reliable development environment)

**Comment by leeoniya** [comment]
> Is there a way to manually override browser version check ?

there are no explicit browsrr checks. it's likely that we've started using a web api that is simply not available in old browsers.

can you open up the webkit/safari console/devtools and see if there are any errors you can report?

if it turns out to be something easy to work around, we will certainly try. but to be clear, this is an inevitability -- at some point it will be unavoidable.

**Comment by SaKiEQ** [comment]
and the offending section seems to stop here. 
Weirdly all other elements further down are properly formatted, what is highlighted in red is a mess - so very hard 
to read and understand. 

![Screen Shot 2022-03-02 at 8 50 53 PM](https://user-images.githubusercontent.com/35499064/156419413-26185ca3-7764-4128-ac04-3dab9c8c8417.jpg)
