### ISSUE TITLE
[Bug] "d.join is not a function" error using numeric template variable in ElasticSearch

### ISSUE THREAD

**Issue by devopstt** [grafana/grafana#5088]
Hi,

Grafana Version: 3.0.2, commit: v3.0.1+21-g0c345e2
Datasource: ElasticSearch
OS: Ubuntu 14.04.2 LTS / 3.13.0-57-generic

after upgrading to 3.x from 2.x some of my templating variables for ElasticSearch did not work longer. I still can see the preview of the data found in the templating section.
But if I use the variable in my ElasticSearch query I only get "d.join is not a function" in the upper left corner.
I figured out it depends on the type of data field in ElasticSearch. If the field is "integer" I will get the mentioned error ("long" also seems not to work). If I store numbers in a "string" field everything works fine.

My template query looks like this:
`{"find":"terms", "field":"someIntegerField"}`

The Grafana query:
```
Metric: Count
Group by Filters: someIntegerField:$myTemplateVariable
Then by Date Histogram: @timestamp
```

I use ElasticSearch 1.7.3. I tried to set the version to 1.x in the datasource section but nothing changed. This is the error I can see in the javascript console:
```
Error: d.join is not a function
this.formatValue@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:10:30824
this.replace/<@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:10:31861
ca.Call@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:4:4095
@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:4:7460
ca.Call@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:4:4095
ja@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:4:7637
this.replace@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:10:31584
h/this.query@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:13:14243
.execute/i</f.prototype.issueQueries@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:40:15067
.execute/i</h.prototype.issueQueries@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:17:10478
h@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:35:19121
i/<@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:35:19293
vc/this.$get</n.prototype.$eval@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:35:26806
vc/this.$get</n.prototype.$digest@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:35:25310
vc/this.$get</n.prototype.$apply@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:35:27091
gg[b]</<.compile/</<@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:37:29816
aa.event.dispatch@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:32:9870
aa.event.add/q.handle@https://x.x.x.x/grafana/public/app/boot.4595d54e.js:32:6657

https://x.x.x.x/grafana/public/app/boot.4595d54e.js
Line 35
```

I hope it helps to reproduce the issue.

Thanks and regards

**Comment by torkelo** [comment]
could you show the response from the Elasticsearch query that is generating the error ?

**Comment by devopstt** [comment]
Thanks for the promt response.

I dont see any requests to the ElasticSearch in the devoloper tab (I will have a look at the network layer later). I think the error happens right before sending any data to the datasource.

**Comment by torkelo** [comment]
think this was fixed in this commit  :)
https://github.com/grafana/grafana/commit/e0e8fd663776a995142aa87565c282c11b3a9ed0

**Comment by devopstt** [comment]
@torkelo Great job! Thanks for your fast reaction.
