### ISSUE TITLE
Dashboards: repeated rows get mixed up

### ISSUE THREAD

**Issue by MnlK** [grafana/grafana#96537]
### What happened?

Since upgrading to 11.3.0, when multiple definitions of repeated rows are used on the same dashboard, the generated rows may get mixed up with other rows instead of being repeated consecutively. The generated rows may mix between any other rows, seemingly random.

![Image](https://github.com/user-attachments/assets/061cdc46-9b0d-4b7b-b44b-ec423a103e54)

### What did you expect to happen?

The rows should be repeated consecutively. 

The rows of the picture should be ordered like:
- repeat 1 -> a
- repeat 1 -> b
- repeat 2 -> a
- repeat 2 -> b

### Did this work before?

Haven't noticed any problems like this with our previously used version 11.2.2

### How do we reproduce it?

1. create new dashboard
2. add 2 empty rows
3. add variable with 2 custom values and multi-select ("a", "b")
4. adapt first row to repeat for this variable
5. adapt second row to repeat for this variable
6. select both/all values for the variable

or import this dashboard json:
[grafana-repeated-rows.json](https://github.com/user-attachments/files/17774447/grafana-repeated-rows.json)

### Environment (with versions)?

Grafana: 11.3.0
OS: Kubuntu 24.04
Browser: Firefox 132

### Grafana platform?

I don't know

**Comment by epochstamp** [comment]
Interested by this fix, I am also experiencing repeating row issues.
_Is it related to how grid coordinates are computed for rows ?_
