### ISSUE TITLE
Getting ERROR from browsers after upgrading grafana 8.5.5 to 9.0.2

### ISSUE THREAD

**Issue by taavit21** [grafana/grafana#51532]
Hello,

This is the log that was actually captured by browser:

`An unexpected error happened
TypeError: Object(...) is not a function

t@https://graylog.agri.ee/grafana/public/plugins/grafana-clock-panel/module.js:2:15546
div
Bl@https://graylog.agri.ee/grafana/public/build/4027.8dfc68b1a209650f62f9.js:3111:467
section
ie@https://graylog.agri.ee/grafana/public/build/97.7e976d9dfaf3b3e213b2.js:26:206
div
c@https://graylog.agri.ee/grafana/public/build/97.7e976d9dfaf3b3e213b2.js:1:264
pe@https://graylog.agri.ee/grafana/public/build/97.7e976d9dfaf3b3e213b2.js:26:13041
g@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:1096373
div
16145/Uo<@https://graylog.agri.ee/grafana/public/build/DashboardPage.53b203c85adb3a57b1ac.js:532:6224
i@https://graylog.agri.ee/grafana/public/build/7638.faf3eabaa2e49b472d37.js:1:28087
u@https://graylog.agri.ee/grafana/public/build/7638.faf3eabaa2e49b472d37.js:1:12893
c@https://graylog.agri.ee/grafana/public/build/DashboardPage.53b203c85adb3a57b1ac.js:548:2800
div
u@https://graylog.agri.ee/grafana/public/build/DashboardPage.53b203c85adb3a57b1ac.js:548:15086
div
div
t@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:1265901
div
Vo@https://graylog.agri.ee/grafana/public/build/DashboardPage.53b203c85adb3a57b1ac.js:532:2960
g@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:1096373
div
div
div
t@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:777260
c@https://graylog.agri.ee/grafana/public/build/4027.8dfc68b1a209650f62f9.js:314:410
div
div
ri@https://graylog.agri.ee/grafana/public/build/DashboardPage.53b203c85adb3a57b1ac.js:532:7263
DashboardPage
g@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:1096373
n@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:1042704
Do@https://graylog.agri.ee/grafana/public/build/4027.8dfc68b1a209650f62f9.js:8261:23633
t@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:1111691
t@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:1113712
main
t@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:1108309
div
us@https://graylog.agri.ee/grafana/public/build/4027.8dfc68b1a209650f62f9.js:2569:1029
87686/t.KBarProvider@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:358763
11622/c<@https://graylog.agri.ee/grafana/public/build/4027.8dfc68b1a209650f62f9.js:5853:27783
Bl@https://graylog.agri.ee/grafana/public/build/4027.8dfc68b1a209650f62f9.js:3111:467
zl@https://graylog.agri.ee/grafana/public/build/4027.8dfc68b1a209650f62f9.js:3111:1023
y@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:141235
Oo@https://graylog.agri.ee/grafana/public/build/4027.8dfc68b1a209650f62f9.js:8261:23165
l@https://graylog.agri.ee/grafana/public/build/4902.331bf177ac0b86d7f476.js:2:1094416
nl@https://graylog.agri.ee/grafana/public/build/4027.8dfc68b1a209650f62f9.js:8274:115`

**Comment by torkelo** [comment]
Try updating the clock panel to latest version, we have published a new version that works with v9

**Comment by grafanabot** [comment]
Thanks for creating this issue! We think it's missing some basic information. 

Follow the issue template and add additional information that will help us replicate the problem. 
For data visualization issues: 
- Query results from the inspect drawer (data tab & query inspector)
- Panel settings can be extracted in the panel inspect drawer JSON tab

For dashboard related issues: 
- Dashboard JSON can be found in the dashboard settings JSON model view

For authentication, provisioning and alerting issues, Grafana server logs are useful. 

Happy graphing!
