### PR TITLE
Show relevant tag name suggestions for OpenTSDB, closes #3610

### LINKED ISSUE #3610: Show tag name suggestions for OpenTSDB
image

At this point of adding a metric on the graph you already have something plotted, which means you have query response:

image

There is a value in suggesting these tag values in the tag key box.

### PR DESCRIPTION
**Pull request by bobrik**
:bomb: :boom: 

image

### CODE REVIEW

**Comment by torkelo** [comment]
Nice! :heart: will take a look :)

File: public/app/plugins/datasource/opentsdb/datasource.js [hunk 1]
```diff
@@ -208,6 +208,13 @@ function (angular, _, dateMath) {
         dps.push([v, k * 1000]);
       });
 
+      target.tagKeys = Object.keys(md.tags);
```
Comment (torkelo) [inline public/app/plugins/datasource/opentsdb/datasource.js]: storing query results (tags in this case) in the query object is not so good. When new tags appear this will change the persisted query model (and cause unsaved changes warning)

**Comment by bobrik** [comment]
Not complaining about dashboard changes anymore. @torkelo take a look now.

**Comment by utkarshcmu** [comment]
Will this change work for Opentsdb 2.1?

**Comment by bobrik** [comment]
@utkarshcmu do you have OpenTSDB 2.1 installation? If so, can you check that query responses include `tags` and `aggregateTags` keys?

**Comment by utkarshcmu** [comment]
@bobrik Sure, I ll check whether this change works with Opentsdb 2.1 or not asap. :)

**Comment by utkarshcmu** [comment]
@bobrik This PR works with Opentsdb 2.1 but I see some JS errors:

```
Error: $scope.get_data is not a function
$scope.targetBlur@http://localhost:3000/public/app/plugins/datasource/opentsdb/queryCtrl.js:44:9
anonymous/fn@http://localhost:3000/dashboard/db/micku1?panelId=2&fullscreen&edit line 13854 > Function:2:218
ngEventHandler/</callback@http://localhost:3000/public/vendor/angular/angular.js:24278:17
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:3000/public/vendor/angular/angular.js:16554:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/public/vendor/angular/angular.js:16654:20
ngEventHandler/<@http://localhost:3000/public/vendor/angular/angular.js:24283:17
jQuery.event.dispatch@http://localhost:3000/public/vendor/jquery/dist/jquery.js:4434:15
jQuery.event.add/elemData.handle@http://localhost:3000/public/vendor/jquery/dist/jquery.js:4121:6
```

Also, now tag keys are suggested according to metrics. What about tag values? Shouldn't they be relevant too? They are irrelevant right now as we use suggest API for getting the tag value suggestions. What do you think about completely deprecating suggest API and rely on lookup API to make the UI more user friendly and avoid any confusions?

**Comment by bobrik** [comment]
Do you see this JS error on master branch?

> Also, now tag keys are suggested according to metrics. What about tag values? Shouldn't they be relevant too?

No.

> They are irrelevant right now as we use suggest API for getting the tag value suggestions. What do you think about completely deprecating suggest API and rely on lookup API to make the UI more user friendly and avoid any confusions?

This requires 2x load on OpenTSDB and not everyone can afford that.

**Comment by utkarshcmu** [comment]
1. I see the above error in master branch. Looks like Opentsdb query editor is kind of broken in master.

2. Lets stay with Suggest API as it will serve most of the use cases, if not all.

**Comment by torkelo** [comment]
Will take a look at OpenTSDB issue after I merge the plugin-editors branch which contain very bin changes for how datasource editors are implemented  (lots of refactoring and changes to how plugins are implemented)

**Comment by utkarshcmu** [comment]
I do not see the above mentioned JS error anymore after panel-editor branch is merged into master. So, that's better. But we still have to resolve #3147, which is a minor bug.

**Comment by bobrik** [comment]
@torkelo let me know when you are finished with refactoring and I can rebase this.

**Comment by torkelo** [comment]
I am done

**Comment by bobrik** [comment]
Done.

File: public/app/plugins/datasource/opentsdb/datasource.js [hunk 2]
```diff
@@ -217,6 +218,13 @@ function (angular, _, dateMath) {
         dps.push([v, k * 1000]);
       });
 
+      tagKeys = Object.keys(md.tags);
+      _.each(md.aggregateTags, function(tag) {
+        tagKeys.push(tag);
+      });
+
+      target.updateTagKeys(tagKeys);
```
Comment (torkelo) [inline public/app/plugins/datasource/opentsdb/datasource.js]: Won't this cause exception if function is undefined  (edited has not been opened yet)

**Comment by bobrik** [comment]
Moved logic to datasource, not keeping anything in query anymore. @torkelo PTAL.

File: public/app/plugins/datasource/opentsdb/datasource.js [hunk 3]
```diff
@@ -87,6 +93,19 @@ function (angular, _, dateMath) {
       return backendSrv.datasourceRequest(options);
     };
 
+    this.suggestTagKeys = function(metric, callback) {
```
Comment (torkelo) [inline public/app/plugins/datasource/opentsdb/datasource.js]: please return promise instead of callback

File: public/app/plugins/datasource/opentsdb/datasource.js [hunk 4]
```diff
@@ -50,6 +53,9 @@ function (angular, _, dateMath) {
           if (index === -1) {
             index = 0;
           }
+
+          saveTagKeys(metricData);
```
Comment (torkelo) [inline public/app/plugins/datasource/opentsdb/datasource.js]: please use this._saveTagKeys  instead, and bind enclosing function to this (will let you remove the saveTagKeys variable at the top)

**Comment by torkelo** [comment]
@bobrik that looks great, just some nitpicking stuff left

**Comment by bobrik** [comment]
It should be done now

**Comment by torkelo** [comment]
@bobrik great! thank you! and sorry for all the nitpicking changes,
