### ISSUE TITLE
Notification policies and contact points are missing after upgrade to 8.3.1

### ISSUE THREAD

**Issue by manojm321** [grafana/grafana#42957]
**What happened**:
Upgraded grafana from 8.0.6 to 8.3.1. With 8.0.6 we had feature_toggles set to `enable=ngalert`. We had bunch of contact points & notification policies configured, but nothing shows up on the corresponding pages. 

**What you expected to happen**:
Notification policies/contact points to persist.

**Environment**:
- Grafana version: 8.3.1 via docker image 'grafana/grafana:8.3.1'
- OS Grafana is installed on: K8s
- User OS & Browser: Mac, Firefox

**Comment by tonedefdev** [comment]
I just upgrade from 8.1.2 > 8.3.1 and every single query for Azure Metrics/Logs are completely missing. I tried to roll back to 8.1.2 but they're still missing. This is definitely a MAJOR issue!

**Comment by tonedefdev** [comment]
Here's some error messages I'm seeing on our panel that is attached to an alert. This is the `A` query that the alert is saying is missing:
```text
An unexpected error happened
Details
TypeError: C.current.editor.onDidChangeMarkers is not a function

    at ue (https://grafana.server.com/public/build/react-monaco-editor.fab5d6bbd438adca1160.js:1:12022)
    at he (https://grafana.server.com/public/build/react-monaco-editor.fab5d6bbd438adca1160.js:1:15841)
    at _s (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:2147:3811)
    at div
    at Ds (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:2147:5799)
    at WithTheme(undefined)
    at c (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:6495:20142)
    at div
    at te (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:6495:31368)
    at Q (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:6495:54021)
    at div
    at K (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:6495:54702)
    at Sl (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:2868:458)
    at Tl (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:2868:1006)
    at div
    at div
    at div
    at https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:584951
    at f (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:498533)
    at Uo (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:586322)
    at Ho (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:586440)
    at c (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:4225:962)
    at div
    at S (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:5795:544)
    at div
    at https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:588664
    at f (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:498533)
    at f (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:496188)
    at oo (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:571697)
    at t (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:504956)
    at io (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:575435)
    at d (https://grafana.server.com/public/build/487.fab5d6bbd438adca1160.js:82:810)
    at div
    at div
    at div
    at div
    at div
    at t (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:657030)
    at u (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:262:1038)
    at L (https://grafana.server.com/public/build/3453.fab5d6bbd438adca1160.js:5:388)
    at We (https://grafana.server.com/public/build/DashboardPage.fab5d6bbd438adca1160.js:167:323)
    at div
    at $r (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:2427:31)
    at div
    at https://grafana.server.com/public/build/DashboardPage.fab5d6bbd438adca1160.js:177:1639
    at div
    at div
    at t (https://grafana.server.com/public/build/DashboardPage.fab5d6bbd438adca1160.js:426:3233)
    at div
    at t (https://grafana.server.com/public/build/DashboardPage.fab5d6bbd438adca1160.js:426:5184)
    at div
    at t (https://grafana.server.com/public/build/DashboardPage.fab5d6bbd438adca1160.js:426:3233)
    at div
    at t (https://grafana.server.com/public/build/DashboardPage.fab5d6bbd438adca1160.js:426:5184)
    at _r (https://grafana.server.com/public/build/DashboardPage.fab5d6bbd438adca1160.js:426:10798)
    at div
    at div
    at ia (https://grafana.server.com/public/build/DashboardPage.fab5d6bbd438adca1160.js:486:6049)
    at v (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:971570)
    at div
    at Mi (https://grafana.server.com/public/build/DashboardPage.fab5d6bbd438adca1160.js:574:3581)
    at DashboardPage
    at v (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:971570)
    at n (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:942012)
    at zi (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:6393:193)
    at t (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:989568)
    at t (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:991589)
    at main
    at t (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:986186)
    at div
    at Ws (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:2156:1022)
    at d (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:4480:26194)
    at Sl (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:2868:458)
    at Tl (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:2868:1006)
    at l (https://grafana.server.com/public/build/633.fab5d6bbd438adca1160.js:2:969088)
    at Oo (https://grafana.server.com/public/build/7095.fab5d6bbd438adca1160.js:6473:384)
```

**Comment by kathy-lee** [comment]
I have the same missing contact points & notification policies, the provisioning/notifiers/notifiers.yml is loaded, but the Grafana UI doesn't show it at all. Hope some can help with this.

**Comment by hiloyt** [comment]
@tonedefdev exactly this same situation, but in my case, it's just pure Thanos (Prometheus) configuration. 8.3.0 and above causing missing queries from query A, you can't edit it or save, because Grafana says "missing data source <id>".

**Comment by kathy-lee** [comment]
I tried the latest Grafana 8.3.2, it's the same missing problem "contact points & notification policies" for me. Could someone help here?

**Comment by luka5** [comment]
I was able to reproduce this with different grafana versions, which I started from scratch. When adding a file in `/etc/grafana/provisioning/notifiers` it works until version 8.2.7. Starting with version 8.3.0 it gets ignored. I see no errors messages. Therefore the error must have been introduced in https://github.com/grafana/grafana/compare/v8.3.0...v8.2.7

**Comment by kathy-lee** [comment]
@luka5 Thanks for checking, but according to your result, I tried v8.2.6, it seems also missing for me:
<img width="1343" alt="Screenshot 2021-12-20 at 12 06 20" src="https://user-images.githubusercontent.com/31970955/146758198-e14aaa00-8254-4162-92cb-9e0db7552cb5.png">

**Comment by mogaal** [comment]
@luka5 Thanks for that

I was facing the same and I can confirm that (at least for me) v8.2.6 doesn't have the issue: reverted and everything started working perfectly and my notifiers are there.

**Comment by kathy-lee** [comment]
With legacy alerting for v8.2.6, it can show notifiers;
With unified alerting(need opt-in) for v8.2.6, it cannot show notifiers.

**Comment by kathy-lee** [comment]
After upgrading to 8.3.4, it could not load notifiers.yml as before.

**Comment by woloss** [comment]
> After upgrading to 8.3.4, it could not load notifiers.yml as before.

Yep. I guess they still didn't rewrite provisioning (at least test-configs for old alerting). If you really want to use latest version, you can try to change grafana.ini "[alerting] enabled = true" and "[unified_alerting] enabled = false".

**Comment by nnedkov-limechain** [comment]
> 

Still, no success I've tried to switch back to legacy alerting but no success. v.8.4.0-beta1

**Comment by nnedkov-limechain** [comment]
> > After upgrading to 8.3.4, it could not load notifiers.yml as before.
> 
> Yep. I guess they still didn't rewrite provisioning (at least test-configs for old alerting). If you really want to use latest version, you can try to change grafana.ini "[alerting] enabled = true" and "[unified_alerting] enabled = false".

Still, no success I've tried to switch back to legacy alerting but no success. v.8.4.0-beta1

**Comment by BastianSperrhacke-Otto** [comment]
For me switching off the unified_alerting and switching on the alerting worked with grafana 8.3.6

**Comment by j-marz** [comment]
> > After upgrading to 8.3.4, it could not load notifiers.yml as before.
> 
> Yep. I guess they still didn't rewrite provisioning (at least test-configs for old alerting). If you really want to use latest version, you can try to change grafana.ini "[alerting] enabled = true" and "[unified_alerting] enabled = false".

This allowed me to provision legacy panel alerts and notifiers from file on grafana/grafana:latest docker image (v8.4.2).

Is config file provisioning supported for grafana's new unified alerting? I can't find any references or differences in the [provisioning documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/)?

**Comment by fakehec** [comment]
Got exactly the same problem today.

I was able to fix it following the next steps, on an Ubuntu installation:

Stop grafana server
#> systemctl stop grafana-server.service

Make backups of the config database, to be safe
#> cd /var/lib/grafana
#> cp -a grafana.db grafana-bak.db
#> sqlite3 grafana.db ‘.clone grafana-dump.db’

Open the config database with sqlitebrowser o similar
#> sqlitebrowser grafana.db

On the “Browser Data” tab , open “alert configuration” table. Your old lost config should be there, but the last entry should be the default empty config, refering to “grafana-default-email”. If that is the case, delete that last entry of the table.

Save the modified database file from sqlitebrowser, and close sqlitebrowser

Start grafana, and lost config of contact points and policies should be back
#> systemctl start grafana-server.service

The problem should be fixed now.

Note: for some reason sometimes the access to the database is locked, and when it happens, the new alert system ngalert loads a default configuration and saves it at the database table “alert_configuration”. Next time ngalert access the database, it find the last entry of the table with the default config dont apply the former config entries.

Hope this helps!

**Comment by grobinson-grafana** [comment]
Would it be possible to update to Grafana 8.5.6? I am interested to see if the issue is still present in the latest 8.5 version as we have made a number of fixes and improvements since 8.3.

**Comment by manojm321** [comment]
Shortly after the issue, we went ahead and recreated the alerts. Since then, I have updated multiple times, right now at 8.5.4, and didn't see any issues.

**Comment by vpradeepkum** [comment]
we are still observing this issue on grafana 9.0.6..

**Comment by GuillaumeCavelier** [comment]
It seems that contact points should now be declared in `/alerting` and not `/notifiers`

**Comment by stmax82** [comment]
@grobinson-grafana provisioning alerts using /etc/grafana/provisioning/notifiers stopped working in 8.3.0 and still isn't working up to 9.3.1...

I don't see any breaking changes in the [release notes for 8.3.0](https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-3-0/).

```
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:7.5.17 # works
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.0.7 # works
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.1.8 # works
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.2.7 # works
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.3.0 # fails
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.3.1 # fails
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.3.2 # fails
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.3.5 # fails
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.3.11 # fails
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.4.11 # fails
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:8.5.15 # fails
docker run --rm -it -p 3000:3000 -v /tmp/grafana:/etc/grafana/provisioning  grafana/grafana:9.3.1 # fails
```

/tmp/grafana/notifiers/default.yml contains:

```
notifiers:
  - name: 'MyAlerts'
    type: email
    uid: myalerts
    org_name: Main Org.
    is_default: true
    settings:
      addresses: 'me@example.com'
```

* Result up to 8.2.7: /alerting/notifications shows "MyAlerts".
* Result starting at 8.3.0: /alerting/notifications does not show "MyAlerts".
