### PR TITLE
GroupingToMatrix: Type fix to resolve `localeCompare` error

### LINKED ISSUE #81440: Transformations: Getting 'h.localeCompare is not a function' error when applying Sort by after Grouping to Matrix
### What happened?

When I apply a 'Sort by' transformation after a 'Grouping to Matrix' transformation, the panel will throw an error if I sort by the primary column of the pivoted data. No error is thrown if I sort by a different column. Attempting to rename the primary column using 'Organize fields by name' before applying the Sort by doesn't resolve the issue.
image
image
image

### What did you expect to happen?

I expected to be able to not encounter an error when sorting the the primary column; I have a use case where I'd like to control the sorted order direction.

### Did this work before?

This is broken for me running Grafana v10.2.3, and appears to be broken on v10.4.0 as well on [Grafana Play](https://play.grafana.org/). Potentially worked on v9.4.3 but can't confidently remember.

### How do we reproduce it?

1. Create a new panel and a query with 3 columns (e.g. using gdev-testdata Data Source with 'CSV Content' mode on [Grafana Play](https://play.grafana.org/)).
2. Add a Grouping to Matrix transformation.
3. Add a subsequent Sort by transformation and select the primary column of the pivot table as the field.

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | table @ 10.4.0-65039 |
| Grafana | 10.4.0-65039 (da894994d42ee2bde00f2366fe6d30ad00b0e907) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "type": "table",
      "title": "Reproduced with embedded data",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "fields": [
                  {
                    "name": "col1",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "col2",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "col3",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "a",
                    "a",
                    "a",
                    "b",
                    "b",
                    "b"
                  ],
                  [
                    1,
                    2,
                    3,
                    1,
                    2,
                    3
                  ],
                  [
                    "bla",
                    "foo",
                    "bar",
                    "x",
                    "a",
                    "z"
                  ]
                ]
              }
            }
          ]
        }
      ],
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": "auto",
            "cellOptions": {
              "type": "auto"
            },
            "inspect": false
          },
          "unitScale": true,
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          },
          "color": {
            "mode": "thresholds"
          }
        },
        "overrides": []
      },
      "transformations": [
        {
          "id": "groupingToMatrix",
          "options": {
            "columnField": "col1",
            "rowField": "col2",
            "valueField": "col3"
          }
        },
        {
          "id": "sortBy",
          "options": {
            "fields": {},
            "sort": [
              {
                "field": "col2\\col1",
                "desc": false
              }
            ]
          }
        }
      ],
      "options": {
        "showHeader": true,
        "cellHeight": "sm",
        "footer": {
          "show": false,
          "reducer": [
            "sum"
          ],
          "countRows": false,
          "fields": ""
        }
      },
      "pluginVersion": "10.4.0-65039"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >table @ 10.4.0-65039</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-testdata-datasource]</td>\n    </tr>\n    <tr>\n      <th>Transform</th>\n      <td>groupingToMatrix, sortBy</td>\n  </tr>\n    <tr><th>Data</th><td> 1 frames, 3 fields, 6 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.4.0-65039 (da894994d42ee2bde00f2366fe6d30ad00b0e907) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"uid\": \"9cY0WtPMz\",\n    \"type\": \"grafana-testdata-datasource\"\n  },\n  \"type\": \"table\",\n  \"title\": \"Panel Title\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"w\": 12,\n    \"h\": 8\n  },\n  \"id\": 12,\n  \"targets\": [\n    {\n      \"scenarioId\": \"csv_content\",\n      \"refId\": \"A\",\n      \"datasource\": {\n        \"type\": \"grafana-testdata-datasource\",\n        \"uid\": \"9cY0WtPMz\"\n      },\n      \"alias\": \"\",\n      \"csvContent\": \"col1, col2, col3\\r\\na, 1, bla\\r\\na, 2, foo\\r\\na, 3, bar\\r\\nb, 1, x\\r\\nb, 2, a\\r\\nb, 3, z\"\n    }\n  ],\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"align\": \"auto\",\n        \"cellOptions\": {\n          \"type\": \"auto\"\n        },\n        \"inspect\": false\n      },\n      \"unitScale\": true,\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      },\n      \"color\": {\n        \"mode\": \"thresholds\"\n      }\n    },\n    \"overrides\": []\n  },\n  \"transformations\": [\n    {\n      \"id\": \"groupingToMatrix\",\n      \"options\": {\n        \"columnField\": \"col1\",\n        \"rowField\": \"col2\",\n        \"valueField\": \"col3\"\n      }\n    },\n    {\n      \"id\": \"sortBy\",\n      \"options\": {\n        \"fields\": {},\n        \"sort\": [\n          {\n            \"field\": \"col2\\\\col1\",\n            \"desc\": false\n          }\n        ]\n      }\n    }\n  ],\n  \"options\": {\n    \"showHeader\": true,\n    \"cellHeight\": \"sm\",\n    \"footer\": {\n      \"show\": false,\n      \"reducer\": [\n        \"sum\"\n      ],\n      \"countRows\": false,\n      \"fields\": \"\"\n    }\n  },\n  \"pluginVersion\": \"10.4.0-65039\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above (after transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    },
    {
      "id": 100,
      "title": "Data (before transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": false,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Panel Title // 2024-01-29 01:11:28",
  "tags": [
    "debug",
    "debug-table"
  ],
  "time": {
    "from": "2024-01-29T00:11:28.968Z",
    "to": "2024-01-29T01:11:28.969Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 10.2.3
OS: Debian 4.19.289

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by alexjonspencer1**
**What does this PR do?**

This is a bugfix PR that resolves a type mismatch causing an error with the `localeCompare` JavaScript string method. Field types for the "Grouping to Matrix" transformation were being statically hardcoded, resulting in calling the `stringComparer` with number types! 🚫

In `groupingToMatrix.ts`, I am now assigning the field `type` based on a dynamic value, instead of the problematic behavior of harcoding it to `string`.

This PR also has some extra stuffz: replacing `localeCompare` with `Intl.Collator` (so much speed 🏃💨) and refactoring to some newer Javascript standards (goodbye for loops).

#### Before

image

#### After

image

Fixes https://github.com/grafana/grafana/issues/81440

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

File: packages/grafana-data/src/field/fieldComparers.ts [hunk 1]
```diff
@@ -55,7 +55,11 @@ const stringComparer = (a: string, b: string): number => {
   if (!a || !b) {
     return falsyComparer(a, b);
   }
-  return a.localeCompare(b);
+
```
Comment (alexjonspencer1) [inline packages/grafana-data/src/field/fieldComparers.ts:58]: Not the root cause of the issue anymore - only strings are being passed to the `stringComparer` 😀, BUT taking the opportunity to change the comparer from `localeCompare` to `Intl.Collator`

File: packages/grafana-data/src/transformations/transformers/groupingToMatrix.ts [hunk 2]
```diff
@@ -90,33 +86,32 @@ export const groupingToMatrixTransformer: DataTransformerInfo<GroupingToMatrixTr
...
           matrixValues[columnName][rowName] = value;
-        }
+        });
 
         const fields: Field[] = [
           {
             name: rowColumnField,
             values: rowValues,
-            type: FieldType.string,
+            type: keyRowField.type,
```
Comment (alexjonspencer1) [inline packages/grafana-data/src/transformations/transformers/groupingToMatrix.ts:104]: This is the actual fix here!

File: packages/grafana-data/src/field/fieldComparers.ts [hunk 3]
```diff
@@ -55,7 +55,11 @@ const stringComparer = (a: string, b: string): number => {
...
+  // Using the Intl.Collator object compare method results in much faster string sorting
+  // (estimated 2x as fast) than .localeCompare
+  const compare = new Intl.Collator('en', { sensitivity: 'base' }).compare;
```
Comment (leeoniya) [inline packages/grafana-data/src/field/fieldComparers.ts:61]: the trick is to pull this out of the comparison loop. you want to only instantiate this one time globally.

File: packages/grafana-data/src/transformations/transformers/groupingToMatrix.test.ts [hunk 4]
```diff
@@ -31,7 +31,7 @@ describe('Grouping to Matrix', () => {
       const expected: Field[] = [
         {
           name: 'Time\\Time',
-          type: FieldType.string,
+          type: FieldType.time,
```
Comment (alexjonspencer1) [inline packages/grafana-data/src/transformations/transformers/groupingToMatrix.test.ts:34]: Update tests to correct type which is derived from data, not hardcoded to `string`. Type `time` will call the `timeComparer` field compare function, which handles types 🚀

File: packages/grafana-data/src/transformations/transformers/groupingToMatrix.ts [hunk 5]
```diff
@@ -146,10 +141,7 @@ export const groupingToMatrixTransformer: DataTransformerInfo<GroupingToMatrixTr
 
 function uniqueValues<T>(values: T[]): T[] {
   const unique = new Set<T>();
-
-  for (let index = 0; index < values.length; index++) {
-    unique.add(values[index]);
-  }
+  values.forEach((value) => unique.add(value));
```
Comment (leeoniya) [inline packages/grafana-data/src/transformations/transformers/groupingToMatrix.ts:144]: i dont think you need this loop. you can just do `new Set(values)`

Comment (alexjonspencer1) [reply packages/grafana-data/src/transformations/transformers/groupingToMatrix.ts]: Updated!

**Comment by leeoniya** [comment]
sorry, couple more notes :)

typically, `forEach` is slower than `for` loops. it's not noticeable for 100 values, but can be for 10k values. i think switching to `forEach` here isnt really necessary and makes the diff larger.

additionally, reordering properties alphabetically and insetting empty newlines is maybe something your editor is configured to do? it's best to disable these and keep the diff focused on the functionally relevant changes and easier to review :)

image

**Comment by alexjonspencer1** [comment]
> sorry, couple more notes :)
> 
> typically, `forEach` is slower than `for` loops. it's not noticeable for 100 values, but can be for 10k values. i think switching to `forEach` here isnt really necessary and makes the diff larger.
> 
> additionally, reordering properties alphabetically and inserting empty newlines is maybe something your editor is configured to do? it's best to disable these and keep the diff focused on the functionally relevant changes, making it easier to review :)
> 
> image

No problem! Make sense for the `forEach` vs `for` loops, I've updated the PR 🚀 

Sounds good on the line breaks + alphabetizing. That was the style preference at my former employer (old habits die hard),  but also understand it generates some diff overhead 😆 I've reverted those changes as well.

File: packages/grafana-data/src/transformations/transformers/groupingToMatrix.ts [hunk 6]
```diff
@@ -145,12 +145,7 @@ export const groupingToMatrixTransformer: DataTransformerInfo<GroupingToMatrixTr
 };
 
 function uniqueValues<T>(values: T[]): T[] {
-  const unique = new Set<T>();
-
-  for (let index = 0; index < values.length; index++) {
-    unique.add(values[index]);
-  }
-
```
Comment (drew08t) [inline packages/grafana-data/src/transformations/transformers/groupingToMatrix.ts:153]: Nice!

**Review by drew08t — APPROVED** [review]
LGTM and works as expected! 🚀
