### ISSUE TITLE
Transformations: Getting 'h.localeCompare is not a function' error when applying Sort by after Grouping to Matrix

### ISSUE THREAD

**Issue by aballinEH2** [grafana/grafana#81440]
### What happened?

When I apply a 'Sort by' transformation after a 'Grouping to Matrix' transformation, the panel will throw an error if I sort by the primary column of the pivoted data. No error is thrown if I sort by a different column. Attempting to rename the primary column using 'Organize fields by name' before applying the Sort by doesn't resolve the issue.
![image](https://github.com/grafana/grafana/assets/145640797/560c00df-62f0-4b0f-897b-9617f1eca52f)
![image](https://github.com/grafana/grafana/assets/145640797/b24375fe-85af-48b1-9f7e-c4a2b4430dd4)
![image](https://github.com/grafana/grafana/assets/145640797/7a60d17e-fbd8-42f3-9928-8c45a17ddaa0)

### What did you expect to happen?

I expected to be able to not encounter an error when sorting the the primary column; I have a use case where I'd like to control the sorted order direction.

### Did this work before?

This is broken for me running Grafana v10.2.3, and appears to be broken on v10.4.0 as well on [Grafana Play](https://play.grafana.org/). Potentially worked on v9.4.3 but can't confidently remember.

### How do we reproduce it?

1. Create a new panel and a query with 3 columns (e.g. using gdev-testdata Data Source with 'CSV Content' mode on [Grafana Play](https://play.grafana.org/)).
2. Add a Grouping to Matrix transformation.
3. Add a subsequent Sort by transformation and select the primary column of the pivot table as the field.

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | table @ 10.4.0-65039 |
| Grafana | 10.4.0-65039 (da894994d42ee2bde00f2366fe6d30ad00b0e907) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "type": "table",
      "title": "Reproduced with embedded data",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "fields": [
                  {
                    "name": "col1",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "col2",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "col3",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "a",
                    "a",
                    "a",
                    "b",
                    "b",
                    "b"
                  ],
                  [
                    1,
                    2,
                    3,
                    1,
                    2,
                    3
                  ],
                  [
                    "bla",
                    "foo",
                    "bar",
                    "x",
                    "a",
                    "z"
                  ]
                ]
              }
            }
          ]
        }
      ],
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": "auto",
            "cellOptions": {
              "type": "auto"
            },
            "inspect": false
          },
          "unitScale": true,
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          },
          "color": {
            "mode": "thresholds"
          }
        },
        "overrides": []
      },
      "transformations": [
        {
          "id": "groupingToMatrix",
          "options": {
            "columnField": "col1",
            "rowField": "col2",
            "valueField": "col3"
          }
        },
        {
          "id": "sortBy",
          "options": {
            "fields": {},
            "sort": [
              {
                "field": "col2\\col1",
                "desc": false
              }
            ]
          }
        }
      ],
      "options": {
        "showHeader": true,
        "cellHeight": "sm",
        "footer": {
          "show": false,
          "reducer": [
            "sum"
          ],
          "countRows": false,
          "fields": ""
        }
      },
      "pluginVersion": "10.4.0-65039"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >table @ 10.4.0-65039</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-testdata-datasource]</td>\n    </tr>\n    <tr>\n      <th>Transform</th>\n      <td>groupingToMatrix, sortBy</td>\n  </tr>\n    <tr><th>Data</th><td> 1 frames, 3 fields, 6 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.4.0-65039 (da894994d42ee2bde00f2366fe6d30ad00b0e907) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"uid\": \"9cY0WtPMz\",\n    \"type\": \"grafana-testdata-datasource\"\n  },\n  \"type\": \"table\",\n  \"title\": \"Panel Title\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"w\": 12,\n    \"h\": 8\n  },\n  \"id\": 12,\n  \"targets\": [\n    {\n      \"scenarioId\": \"csv_content\",\n      \"refId\": \"A\",\n      \"datasource\": {\n        \"type\": \"grafana-testdata-datasource\",\n        \"uid\": \"9cY0WtPMz\"\n      },\n      \"alias\": \"\",\n      \"csvContent\": \"col1, col2, col3\\r\\na, 1, bla\\r\\na, 2, foo\\r\\na, 3, bar\\r\\nb, 1, x\\r\\nb, 2, a\\r\\nb, 3, z\"\n    }\n  ],\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"align\": \"auto\",\n        \"cellOptions\": {\n          \"type\": \"auto\"\n        },\n        \"inspect\": false\n      },\n      \"unitScale\": true,\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      },\n      \"color\": {\n        \"mode\": \"thresholds\"\n      }\n    },\n    \"overrides\": []\n  },\n  \"transformations\": [\n    {\n      \"id\": \"groupingToMatrix\",\n      \"options\": {\n        \"columnField\": \"col1\",\n        \"rowField\": \"col2\",\n        \"valueField\": \"col3\"\n      }\n    },\n    {\n      \"id\": \"sortBy\",\n      \"options\": {\n        \"fields\": {},\n        \"sort\": [\n          {\n            \"field\": \"col2\\\\col1\",\n            \"desc\": false\n          }\n        ]\n      }\n    }\n  ],\n  \"options\": {\n    \"showHeader\": true,\n    \"cellHeight\": \"sm\",\n    \"footer\": {\n      \"show\": false,\n      \"reducer\": [\n        \"sum\"\n      ],\n      \"countRows\": false,\n      \"fields\": \"\"\n    }\n  },\n  \"pluginVersion\": \"10.4.0-65039\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above (after transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    },
    {
      "id": 100,
      "title": "Data (before transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": false,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Panel Title // 2024-01-29 01:11:28",
  "tags": [
    "debug",
    "debug-table"
  ],
  "time": {
    "from": "2024-01-29T00:11:28.968Z",
    "to": "2024-01-29T01:11:28.969Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 10.2.3
OS: Debian 4.19.289

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by aballinEH2** [comment]
I was able to get around this by adding a 'Convert field type' transformation between the grouping and sorting transformations. Converting to either String (which the column already is) or Number both work.

**Comment by levynir** [comment]
I can confirm this happens can be reproduced on the OS version Grafana v10.0.3 (eb8dd72637)

MySQL connection
```
SELECT COUNT(*) as c, 
      DATE(date_created) d, 
      "xxxx" as channel 
FROM yyy 
WHERE zzz = ${ccc}
GROUP BY 2
```
then apply this transformation
![image](https://github.com/grafana/grafana/assets/5058191/68062b66-dbf7-45e0-9cc1-1dea34bc0ecc)

the panel loads forever and the "cancel query" button does not work.
![image](https://github.com/grafana/grafana/assets/5058191/9b2f27d7-e16c-4099-9a8f-2a567fd20df4)

The JS console shows this error:
```
TypeError: d.localeCompare is not a function
    at o (fieldComparers.ts:62:12)
    at fieldComparers.ts:114:47
    at Array.sort (<anonymous>)
    at b (processDataFrame.ts:430:9)
    at sortBy.ts:49:14
    at Array.map (<anonymous>)
    at de (sortBy.ts:46:15)
    at sortBy.ts:40:16
    at map.js:7:37
    at E._next (OperatorSubscriber.js:15:21)
o       @       fieldComparers.ts:62
(anonymous)     @       fieldComparers.ts:114
b       @       processDataFrame.ts:430
(anonymous)     @       sortBy.ts:49
de      @       sortBy.ts:46
(anonymous)     @       sortBy.ts:40
(anonymous)     @       TransformationEditor.tsx:53
setTimeout (async)
(anonymous)     @       TransformationEditor.tsx:53

```
