### ISSUE TITLE
Product Area: getAvailableIcons is not a function in 12.1.0

### ISSUE THREAD

**Issue by vitPinchuk** [grafana/grafana#106006]
### What happened?

When using the `getAvailableIcons` function from `@grafana/ui` in Grafana version 12.1, it results in an error that completely breaks the plugin.

Environment:

Grafana Version: 12.1
Deployment: Docker image

![Image](https://github.com/user-attachments/assets/ed62d2bc-e1f4-4256-a98f-a572d45ecaa3)

### What did you expect to happen?

The getAvailableIcons function should work without causing errors or breaking the plugin.

### Did this work before?

Yes
It works fine in 12.0

### How do we reproduce it?

Steps to Reproduce:

Use getAvailableIcons from @grafana/ui in a plugin.
Run the plugin in Grafana 12.1 via Docker image.
Observe the error and plugin failure.

### Environment (with versions)?

Grafana: 12.1.0

### Grafana platform?

Docker

**Comment by vitPinchuk** [comment]
@tomglenn @hugohaggmark  
Thanks for the quick response
`getAvailableIcons` now works properly in the Grafana main and does not cause any issues.
There is still an issue with `getFieldTypeIcon` from `@grafana/ui` in Grafana version 12.1, I also mentioned it in the problem description.
I would be glad if you could fix this issue too. Thank you very much

Should I open a new issue for that? 
![Image](https://github.com/user-attachments/assets/e2534ffb-fd50-4af0-80b7-73309ff2aa72)
