### ISSUE TITLE
$__interval_ms javascript error with v5.2.1

### ISSUE THREAD

**Issue by miguel-diez** [grafana/grafana#12600]
### What Grafana version are you using?

5.2.1

### What datasource are you using?

Prometheus 2.3.2

### What OS are you running grafana on?

Centos 7

### What did you do?

Previously I was working with Grafana 4.6.3 without issues, but after upgrading to 5.2.1, I'm not able to use $__interval_ms variables in Graph and Singlestat panels. I'm getting a javascript error "t.replace is not a function". 

$__interval is working right.

The metric example: sum(rate(iis_requests_total[$__interval])*$__interval_ms/1000)

Panel data error: TypeError: t.replace is not a function
    at a (datasource.ts:96)
    at t.interpolateQueryExpr (datasource.ts:174)
    at t.formatValue (template_srv.ts:92)
    at template_srv.ts:195
    at String.replace (<anonymous>)
    at t.replace (template_srv.ts:189)
    at t.createQuery (datasource.ts:271)
    at t.query (datasource.ts:204)
    at e.issueQueries (metrics_panel_ctrl.ts:276)
    at e.issueQueries (module.ts:229)

Regards

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/12533
