### ISSUE TITLE
Loki: Panels with 'step' field in JSON target break after upgrade from v9 to v10/v11

### ISSUE THREAD

**Issue by OscarVanL** [grafana/grafana#92574]
### What happened?

After upgrading my Grafana instance from 9.5.2 several of our Loki panels stopped working and reported errors like: `s?.match is not a function` and `H.replace is not a function`.

We did an incremental upgrade from 9.5.2 to 10.* (where we first saw the regression), and then to 11.2.0 (where we still see the regression).

The panels look like this:
![Image](https://github.com/user-attachments/assets/bc7fe3fa-74e3-4e4e-9c53-8bf7d803b03e)

The full stack trace (visible when editing the affected panel on the 'Query' tab) is:
```
TypeError: m.trim is not a function

    at https://my.selfhosted.grafana/public/build/9430.7b7e47433c913d48d652.js:122:8966
    at div
    at b (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:12:67564)
    at u (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:12:65702)
    at https://my.selfhosted.grafana/public/build/9430.7b7e47433c913d48d652.js:164:770
    at Zi (https://my.selfhosted.grafana/public/build/9430.7b7e47433c913d48d652.js:164:4080)
    at s (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:1:183)
    at g (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:63:134080)
    at a (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:63:134589)
    at div
    at div
    at div
    at yu (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:106:22933)
    at Gu (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:43:352919)
    at ia (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:106:27246)
    at ka (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:106:27362)
    at v (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:292:68)
    at div
    at K (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:3070:70)
    at div
    at xh (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:106:34671)
    at Gu (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:43:352919)
    at mt (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:47:530)
    at dh (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:106:18491)
    at An (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:53:799)
    at kc (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:106:20207)
    at l (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:3071:6294)
    at div
    at div
    at div
    at div
    at div
    at q (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:859:18761)
    at l (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:63:33933)
    at q (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:3076:56)
    at Ua (https://my.selfhosted.grafana/public/build/DashboardPageProxy.3604d9a6305816aecdaf.js:3:9734)
    at div
    at s (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:155:62580)
    at div
    at https://my.selfhosted.grafana/public/build/DashboardPageProxy.3604d9a6305816aecdaf.js:3:11198
    at div
    at div
    at o (https://my.selfhosted.grafana/public/build/660.a5b43edd4f587a934f90.js:1:2310)
    at div
    at o (https://my.selfhosted.grafana/public/build/660.a5b43edd4f587a934f90.js:1:4298)
    at G (https://my.selfhosted.grafana/public/build/660.a5b43edd4f587a934f90.js:1:9639)
    at div
    at o (https://my.selfhosted.grafana/public/build/660.a5b43edd4f587a934f90.js:1:2310)
    at div
    at o (https://my.selfhosted.grafana/public/build/660.a5b43edd4f587a934f90.js:1:4298)
    at G (https://my.selfhosted.grafana/public/build/660.a5b43edd4f587a934f90.js:1:9639)
    at div
    at div
    at div
    at V (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:229:21920)
    at Ja (https://my.selfhosted.grafana/public/build/DashboardPageProxy.3604d9a6305816aecdaf.js:3:14059)
    at Ji (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:1427:122331)
    at WithTheme(Connect(Ja))
    at bs (https://my.selfhosted.grafana/public/build/DashboardPageProxy.3604d9a6305816aecdaf.js:3:25337)
    at DashboardPage
    at Ji (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:1427:122331)
    at Ps (https://my.selfhosted.grafana/public/build/DashboardPageProxy.3604d9a6305816aecdaf.js:3:32405)
    at Suspense
    at g (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:63:134080)
    at mu (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:4418:11814)
    at I (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:997:29132)
    at wo (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:988:4451)
    at ms (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:988:12000)
    at Vt (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:997:17388)
    at I (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:997:31288)
    at div
    at https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:82:52960
    at main
    at div
    at div
    at div
    at Pg (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:4418:2373)
    at div
    at Hc (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:4418:7141)
    at wo (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:988:4451)
    at ms (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:988:12000)
    at _s (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:988:11336)
    at Sr (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:997:17687)
    at y (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:5:284076)
    at I (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:997:25385)
    at v (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:164:9002)
    at E (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:1427:112967)
    at o (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:335:27877)
    at g (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:63:134080)
    at a (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:63:134589)
    at ht (https://my.selfhosted.grafana/public/build/3855.c53eb219979d7cb3b2d4.js:1431:508)
    at bu (https://my.selfhosted.grafana/public/build/3729.ffff83737929c19134ef.js:4418:13861)
```

### What did you expect to happen?

The Loki panels should have continued to work, and not produce errors.

### Did this work before?

This worked on Grafana v9.5.2

### How do we reproduce it?

1. Create a New Dashboard
2. Add a Loki Panel and save
3. Save the dashboard
4. Edit Dashboard Settings and open 'JSON Model' tab
5. Find the loki datasource under "targets" and add `"step": 10`, it should look like this:
```
      "targets": [
        {
          "datasource": {
            "type": "loki",
            "uid": "dfgdfgdfg"
          },
          "editorMode": "code",
          "expr": "{app=\"foo\"}",
          "maxLines": 100,
          "queryType": "range",
          "refId": "A",
          "step": 10
        }
      ],
```
6. Click Save changes and return to the dashboard
7. You should now see the Loki panel is erroring

(N.B. This was not how I originally ended up with "step" in my panels, but this reproduces the problem that I am having)

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | logs @ Grafana v11.2.0 (2a88694fd3) |
| Grafana | Grafana v11.2.0 (2a88694fd3) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "showTime": false,
        "showLabels": false,
        "showCommonLabels": false,
        "wrapLogMessage": false,
        "prettifyLogMessage": false,
        "enableLogDetails": true,
        "dedupStrategy": "none",
        "sortOrder": "Descending"
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": []
        }
      ],
      "title": "Reproduced with embedded data",
      "type": "logs"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >logs @ Grafana v11.2.0 (2a88694fd3)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[loki]</td>\n    </tr>\n    \n    <tr><th>Data</th><td>Error 0 frames, 0 fields, 0 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>Grafana v11.2.0 (2a88694fd3) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"default\": false,\n    \"type\": \"loki\",\n    \"uid\": \"dfgdfgdfg\"\n  },\n  \"gridPos\": {\n    \"h\": 8,\n    \"w\": 12,\n    \"x\": 0,\n    \"y\": 0\n  },\n  \"id\": 1,\n  \"options\": {\n    \"showTime\": false,\n    \"showLabels\": false,\n    \"showCommonLabels\": false,\n    \"wrapLogMessage\": false,\n    \"prettifyLogMessage\": false,\n    \"enableLogDetails\": true,\n    \"dedupStrategy\": \"none\",\n    \"sortOrder\": \"Descending\"\n  },\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"loki\",\n        \"uid\": \"JtT9mganz\"\n      },\n      \"editorMode\": \"code\",\n      \"expr\": \"{app=\\\"foo\\\"}\",\n      \"maxLines\": 100,\n      \"queryType\": \"range\",\n      \"refId\": \"A\",\n      \"step\": 10\n    }\n  ],\n  \"title\": \"Panel Title\",\n  \"type\": \"logs\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Panel Title // 2024-08-28 10:27:14",
  "tags": [
    "debug",
    "debug-logs"
  ],
  "time": {
    "from": "2024-08-28T04:27:14.879Z",
    "to": "2024-08-28T10:27:14.879Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 11.2.0
OS: MacOS Sonoma 14.5 (also reproduced by others on Windows and Ubuntu)
Browser: Chrome 128.0.6613.84

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki 5.0.0

**Comment by OscarVanL** [comment]
@matyax Thanks! I'm unsure how this bad data ended up in our dashboard JSON in the first place, but improving the validation here seems good.

**Comment by matyax** [comment]
@OscarVanL The numeric step can't be processed by Loki (the query will fail because it expects a duration), but the error you reported will be fixed.
