### ISSUE TITLE
Variable selector doesn't work with datasources implementing VariableQueryEditor

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#20525]
**What happened**:
Variable selector failed to load:
![Screenshot from 2019-11-20 17-04-48](https://user-images.githubusercontent.com/4932851/69246013-f88b7b00-0bb8-11ea-8529-517b5878322f.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard, add template variable with type query and one of the datasources implementing its own `VariableQueryEditor` (Splunk, Dynatrace, Stackdriver).

![Screenshot from 2019-11-20 17-05-15](https://user-images.githubusercontent.com/4932851/69246893-97fd3d80-0bba-11ea-8fb6-48398f42c4b9.png)

**Anything else we need to know?**:
There's an error in console:
```
TypeError: query.indexOf is not a function
    at containsSearchFilter (variable.ts:22)
    at ValueSelectDropdownCtrl (value_select_dropdown.ts:32)
```
This behaviour was introduced by cb0e80e7b92c93336901992ade8e2cd73a8d49c2
This PR assumes `query` is a string, but if datasource implements `VariableQueryEditor` it may be arbitrary object. So basic fix may be like:
```ts
export const containsSearchFilter = (query: string): boolean =>
  query && typeof query === 'string' ? query.indexOf(SEARCH_FILTER_VARIABLE) !== -1 : false;
```

**Environment**:
- Grafana version: Grafana v6.5.0-beta1 (ab9c0da30e)

**Comment by hugohaggmark** [comment]
Great catch @alexanderzobnin !
