### PR TITLE
Fix: Wrong swagger meta preventing spec generation

### LINKED ISSUE #53708: Cannot build Go on current main branch
**What happened**:

```
make build-go
(re)installing /Users/user/Work/go/bin/swagger-v0.29.0
SWAGGER_GENERATE_EXTENSION=false /Users/user/Work/go/bin/swagger-v0.29.0 generate spec -m -w pkg/server -o public/api-spec.json \
	-x "github.com/grafana/grafana/pkg/services/ngalert/api/tooling/definitions" \
	-x "github.com/prometheus/alertmanager" \
	-i pkg/api/swagger_tags.json
json: cannot unmarshal string into Go value of type spec.SecuritySchemeProps
make: *** [public/api-spec.json] Error 1
```

or 

```
make deps-go
go run build.go setup
Version: 9.2.0, Linux Version: 9.2.0, Package Iteration: 1660384122pre
go install -v ./pkg/cmd/grafana-server
pkg/server/wire_gen.go:153:2: no required module provides package github.com/grafana/grafana/pkg/api/docs/definitions; to add it:
	go get github.com/grafana/grafana/pkg/api/docs/definitions
pkg/server/wire_gen.go:67:2: no required module provides package github.com/grafana/grafana/pkg/services/encryption/ossencryption; to add it:
	go get github.com/grafana/grafana/pkg/services/encryption/ossencryption
exit status 1
exit status 1
make: *** [deps-go] Error 1
```
**What you expected to happen**:

Build

**How to reproduce it (as minimally and precisely as possible)**:

Run those commands

**Anything else we need to know?**:

Works with 9.0.5 (f3cc54f7ef9c7168d016cac6a7bb3cad2f8b9d28) until

<details>

```
github.com/grafana/grafana/pkg/server
# github.com/grafana/grafana/pkg/server
pkg/server/wire_gen.go:244:20: assignment mismatch: 1 variable but kvstore2.ProvideService returns 2 values
pkg/server/wire_gen.go:244:70: not enough arguments in call to kvstore2.ProvideService
	have (*sqlstore.SQLStore, *"github.com/grafana/grafana/pkg/services/secrets/manager".SecretsService, *"github.com/grafana/grafana/pkg/services/secrets/kvstore".OSSRemoteSecretsPluginCheck)
	want (sqlstore.Store, secrets.Service, "github.com/grafana/grafana/pkg/services/secrets/kvstore".UseRemoteSecretsPluginCheck, "github.com/grafana/grafana/pkg/infra/kvstore".KVStore, featuremgmt.FeatureToggles)
pkg/server/wire_gen.go:294: not enough arguments in call to provisioning.ProvideService
	have (*ossaccesscontrol.OSSAccessControlService, *setting.Cfg, *sqlstore.SQLStore, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *ossencryption.Service, *notifications.NotificationService, *"github.com/grafana/grafana/pkg/services/dashboards/service".DashboardServiceImpl, *"github.com/grafana/grafana/pkg/services/datasources/service".Service, *"github.com/grafana/grafana/pkg/services/dashboards/service".DashboardServiceImpl, *"github.com/grafana/grafana/pkg/services/dashboards/service".FolderServiceImpl, *alerting.AlertNotificationService, *"github.com/grafana/grafana/pkg/services/pluginsettings/service".Service, searchV2.SearchService, quota.Service)
	want (accesscontrol.AccessControl, *setting.Cfg, *sqlstore.SQLStore, "github.com/grafana/grafana/pkg/plugins".Store, encryption.Internal, *notifications.NotificationService, "github.com/grafana/grafana/pkg/services/dashboards".DashboardProvisioningService, "github.com/grafana/grafana/pkg/services/datasources".DataSourceService, correlations.Service, "github.com/grafana/grafana/pkg/services/dashboards".DashboardService, "github.com/grafana/grafana/pkg/services/dashboards".FolderService, *alerting.AlertNotificationService, pluginsettings.Service, searchV2.SearchService, quota.Service)
pkg/server/wire_gen.go:357: not enough arguments in call to api.ProvideHTTPServer
	have ("github.com/grafana/grafana/pkg/api".ServerOptions, *setting.Cfg, *routing.RouteRegisterImpl, *bus.InProcBus, *rendering.RenderingService, *licensing.OSSLicensingService, *hooks.HooksService, *localcache.CacheService, *sqlstore.SQLStore, *alerting.AlertEngine, *validations.OSSPluginRequestValidator, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *"github.com/grafana/grafana/pkg/services/plugindashboards/service".Service, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *loader.Loader, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *setting.OSSImpl, *"github.com/grafana/grafana/pkg/services/datasources/service".CacheServiceImpl, *auth.UserAuthTokenService, *cleanup.CleanUpService, *shorturls.ShortURLService, *queryhistory.QueryHistoryService, thumbs.Service, *remotecache.RemoteCache, *"github.com/grafana/grafana/pkg/services/provisioning".ProvisioningServiceImpl, *loginservice.Implementation, *"github.com/grafana/grafana/pkg/login".AuthenticatorService, *ossaccesscontrol.OSSAccessControlService, *datasourceproxy.DataSourceProxyService, *"github.com/grafana/grafana/pkg/services/search".SearchService, *"github.com/grafana/grafana/pkg/services/live".GrafanaLive, *pushhttp.Gateway, *plugincontext.Provider, *contexthandler.ContextHandler, *featuremgmt.FeatureManager, *ngalert.AlertNG, *librarypanels.LibraryPanelService, *libraryelements.LibraryElementService, quota.Service, *social.SocialService, tracing.Tracer, "github.com/grafana/grafana/pkg/services/export".ExportService, *ossencryption.Service, *updatechecker.GrafanaService, *updatechecker.PluginsService, *searchusers.OSSService, *"github.com/grafana/grafana/pkg/services/datasources/service".Service, *"github.com/grafana/grafana/pkg/services/secrets/manager".SecretsService, *query.Service, *"github.com/grafana/grafana/pkg/services/ldap".OSSGroups, teamguardian.TeamGuardian, *"github.com/grafana/grafana/pkg/services/serviceaccounts/manager".ServiceAccountsService, *authinfoservice.Implementation, "github.com/grafana/grafana/pkg/services/store".HTTPStorageService, *notifications.NotificationService, *"github.com/grafana/grafana/pkg/services/dashboards/service".DashboardServiceImpl, *"github.com/grafana/grafana/pkg/services/dashboards/service".DashboardServiceImpl, *"github.com/grafana/grafana/pkg/services/dashboards/service".FolderServiceImpl, *permissions.OSSDatasourcePermissionsService, *alerting.AlertNotificationService, *"github.com/grafana/grafana/pkg/services/dashboardsnapshots/service".ServiceImpl, *comments.Service, *"github.com/grafana/grafana/pkg/services/pluginsettings/service".Service, *avatar.AvatarCacheServer, pref.Service, "github.com/grafana/grafana/pkg/services/store".EntityEventsService, *ossaccesscontrol.TeamPermissionsService, *ossaccesscontrol.FolderPermissionsService, *ossaccesscontrol.DashboardPermissionsService, dashver.Service, star.Service, csrf.Service, *"github.com/grafana/grafana/pkg/framework/coremodel/registry".Generic, *"github.com/grafana/grafana/pkg/framework/coremodel/registry".Static, playlist.Service, "github.com/grafana/grafana/pkg/infra/kvstore".KVStore, *"github.com/grafana/grafana/pkg/services/secrets/migrator".SecretsMigrator, *"github.com/grafana/grafana/pkg/services/secrets/kvstore".OSSRemoteSecretsPluginCheck, *"github.com/grafana/grafana/pkg/services/publicdashboards/api".Api, user.Service)
	want ("github.com/grafana/grafana/pkg/api".ServerOptions, *setting.Cfg, routing.RouteRegister, bus.Bus, rendering.Service, "github.com/grafana/grafana/pkg/models".Licensing, *hooks.HooksService, *localcache.CacheService, *sqlstore.SQLStore, *alerting.AlertEngine, "github.com/grafana/grafana/pkg/models".PluginRequestValidator, "github.com/grafana/grafana/pkg/plugins".StaticRouteResolver, plugindashboards.Service, "github.com/grafana/grafana/pkg/plugins".Store, "github.com/grafana/grafana/pkg/plugins".Client, "github.com/grafana/grafana/pkg/plugins".ErrorResolver, "github.com/grafana/grafana/pkg/plugins".Manager, setting.Provider, "github.com/grafana/grafana/pkg/services/datasources".CacheService, "github.com/grafana/grafana/pkg/models".UserTokenService, *cleanup.CleanUpService, shorturls.Service, queryhistory.Service, correlations.Service, thumbs.Service, *remotecache.RemoteCache, "github.com/grafana/grafana/pkg/services/provisioning".ProvisioningService, "github.com/grafana/grafana/pkg/services/login".Service, "github.com/grafana/grafana/pkg/login".Authenticator, accesscontrol.AccessControl, *datasourceproxy.DataSourceProxyService, *"github.com/grafana/grafana/pkg/services/search".SearchService, *"github.com/grafana/grafana/pkg/services/live".GrafanaLive, *pushhttp.Gateway, *plugincontext.Provider, *contexthandler.ContextHandler, *featuremgmt.FeatureManager, *ngalert.AlertNG, librarypanels.Service, libraryelements.Service, quota.Service, social.Service, tracing.Tracer, "github.com/grafana/grafana/pkg/services/export".ExportService, encryption.Internal, *updatechecker.GrafanaService, *updatechecker.PluginsService, searchusers.Service, "github.com/grafana/grafana/pkg/services/datasources".DataSourceService, secrets.Service, *query.Service, "github.com/grafana/grafana/pkg/services/ldap".Groups, teamguardian.TeamGuardian, serviceaccounts.Service, "github.com/grafana/grafana/pkg/services/login".AuthInfoService, "github.com/grafana/grafana/pkg/services/store".HTTPStorageService, *notifications.NotificationService, "github.com/grafana/grafana/pkg/services/dashboards".DashboardService, "github.com/grafana/grafana/pkg/services/dashboards".DashboardProvisioningService, "github.com/grafana/grafana/pkg/services/dashboards".FolderService, permissions.DatasourcePermissionsService, *alerting.AlertNotificationService, dashboardsnapshots.Service, *comments.Service, *"github.com/grafana/grafana/pkg/services/pluginsettings/service".Service, *avatar.AvatarCacheServer, pref.Service, "github.com/grafana/grafana/pkg/services/store".EntityEventsService, accesscontrol.TeamPermissionsService, accesscontrol.FolderPermissionsService, accesscontrol.DashboardPermissionsService, dashver.Service, star.Service, csrf.Service, *"github.com/grafana/grafana/pkg/framework/coremodel/registry".Generic, *"github.com/grafana/grafana/pkg/framework/coremodel/registry".Static, playlist.Service, "github.com/grafana/grafana/pkg/infra/kvstore".KVStore, secrets.Migrator, "github.com/grafana/grafana/pkg/services/secrets/kvstore".UseRemoteSecretsPluginCheck, *"github.com/grafana/grafana/pkg/services/publicdashboards/api".Api, user.Service)
pkg/server/wire_gen.go:467:20: assignment mismatch: 1 variable but kvstore2.ProvideService returns 2 values
pkg/server/wire_gen.go:467:70: not enough arguments in call to kvstore2.ProvideService
	have (*sqlstore.SQLStore, *"github.com/grafana/grafana/pkg/services/secrets/manager".SecretsService, *"github.com/grafana/grafana/pkg/services/secrets/kvstore".OSSRemoteSecretsPluginCheck)
	want (sqlstore.Store, secrets.Service, "github.com/grafana/grafana/pkg/services/secrets/kvstore".UseRemoteSecretsPluginCheck, "github.com/grafana/grafana/pkg/infra/kvstore".KVStore, featuremgmt.FeatureToggles)
pkg/server/wire_gen.go:518: not enough arguments in call to provisioning.ProvideService
	have (*ossaccesscontrol.OSSAccessControlService, *setting.Cfg, *sqlstore.SQLStore, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *ossencryption.Service, *notifications.NotificationService, *"github.com/grafana/grafana/pkg/services/dashboards/service".DashboardServiceImpl, *"github.com/grafana/grafana/pkg/services/datasources/service".Service, *"github.com/grafana/grafana/pkg/services/dashboards/service".DashboardServiceImpl, *"github.com/grafana/grafana/pkg/services/dashboards/service".FolderServiceImpl, *alerting.AlertNotificationService, *"github.com/grafana/grafana/pkg/services/pluginsettings/service".Service, searchV2.SearchService, quota.Service)
	want (accesscontrol.AccessControl, *setting.Cfg, *sqlstore.SQLStore, "github.com/grafana/grafana/pkg/plugins".Store, encryption.Internal, *notifications.NotificationService, "github.com/grafana/grafana/pkg/services/dashboards".DashboardProvisioningService, "github.com/grafana/grafana/pkg/services/datasources".DataSourceService, correlations.Service, "github.com/grafana/grafana/pkg/services/dashboards".DashboardService, "github.com/grafana/grafana/pkg/services/dashboards".FolderService, *alerting.AlertNotificationService, pluginsettings.Service, searchV2.SearchService, quota.Service)
pkg/server/wire_gen.go:582: not enough arguments in call to api.ProvideHTTPServer
	have ("github.com/grafana/grafana/pkg/api".ServerOptions, *setting.Cfg, *routing.RouteRegisterImpl, *bus.InProcBus, *rendering.RenderingService, *licensing.OSSLicensingService, *hooks.HooksService, *localcache.CacheService, *sqlstore.SQLStore, *alerting.AlertEngine, *validations.OSSPluginRequestValidator, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *"github.com/grafana/grafana/pkg/services/plugindashboards/service".Service, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *loader.Loader, *"github.com/grafana/grafana/pkg/plugins/manager".PluginManager, *setting.OSSImpl, *"github.com/grafana/grafana/pkg/services/datasources/service".CacheServiceImpl, *auth.UserAuthTokenService, *cleanup.CleanUpService, *shorturls.ShortURLService, *queryhistory.QueryHistoryService, thumbs.Service, *remotecache.RemoteCache, *"github.com/grafana/grafana/pkg/services/provisioning".ProvisioningServiceImpl, *loginservice.Implementation, *"github.com/grafana/grafana/pkg/login".AuthenticatorService, *ossaccesscontrol.OSSAccessControlService, *datasourceproxy.DataSourceProxyService, *"github.com/grafana/grafana/pkg/services/search".SearchService, *"github.com/grafana/grafana/pkg/services/live".GrafanaLive, *pushhttp.Gateway, *plugincontext.Provider, *contexthandler.ContextHandler, *featuremgmt.FeatureManager, *ngalert.AlertNG, *librarypanels.LibraryPanelService, *libraryelements.LibraryElementService, quota.Service, *social.SocialService, tracing.Tracer, "github.com/grafana/grafana/pkg/services/export".ExportService, *ossencryption.Service, *updatechecker.GrafanaService, *updatechecker.PluginsService, *searchusers.OSSService, *"github.com/grafana/grafana/pkg/services/datasources/service".Service, *"github.com/grafana/grafana/pkg/services/secrets/manager".SecretsService, *query.Service, *"github.com/grafana/grafana/pkg/services/ldap".OSSGroups, teamguardian.TeamGuardian, *"github.com/grafana/grafana/pkg/services/serviceaccounts/manager".ServiceAccountsService, *authinfoservice.Implementation, "github.com/grafana/grafana/pkg/services/store".HTTPStorageService, *notifications.NotificationService, *"github.com/grafana/grafana/pkg/services/dashboards/service".DashboardServiceImpl, *"github.com/grafana/grafana/pkg/services/dashboards/service".DashboardServiceImpl, *"github.com/grafana/grafana/pkg/services/dashboards/service".FolderServiceImpl, *permissions.OSSDatasourcePermissionsService, *alerting.AlertNotificationService, *"github.com/grafana/grafana/pkg/services/dashboardsnapshots/service".ServiceImpl, *comments.Service, *"github.com/grafana/grafana/pkg/services/pluginsettings/service".Service, *avatar.AvatarCacheServer, pref.Service, "github.com/grafana/grafana/pkg/services/store".EntityEventsService, *ossaccesscontrol.TeamPermissionsService, *ossaccesscontrol.FolderPermissionsService, *ossaccesscontrol.DashboardPermissionsService, dashver.Service, star.Service, csrf.Service, *"github.com/grafana/grafana/pkg/framework/coremodel/registry".Generic, *"github.com/grafana/grafana/pkg/framework/coremodel/registry".Static, playlist.Service, "github.com/grafana/grafana/pkg/infra/kvstore".KVStore, *"github.com/grafana/grafana/pkg/services/secrets/migrator".SecretsMigrator, *"github.com/grafana/grafana/pkg/services/secrets/kvstore".OSSRemoteSecretsPluginCheck, *"github.com/grafana/grafana/pkg/services/publicdashboards/api".Api, user.Service)
	want ("github.com/grafana/grafana/pkg/api".ServerOptions, *setting.Cfg, routing.RouteRegister, bus.Bus, rendering.Service, "github.com/grafana/grafana/pkg/models".Licensing, *hooks.HooksService, *localcache.CacheService, *sqlstore.SQLStore, *alerting.AlertEngine, "github.com/grafana/grafana/pkg/models".PluginRequestValidator, "github.com/grafana/grafana/pkg/plugins".StaticRouteResolver, plugindashboards.Service, "github.com/grafana/grafana/pkg/plugins".Store, "github.com/grafana/grafana/pkg/plugins".Client, "github.com/grafana/grafana/pkg/plugins".ErrorResolver, "github.com/grafana/grafana/pkg/plugins".Manager, setting.Provider, "github.com/grafana/grafana/pkg/services/datasources".CacheService, "github.com/grafana/grafana/pkg/models".UserTokenService, *cleanup.CleanUpService, shorturls.Service, queryhistory.Service, correlations.Service, thumbs.Service, *remotecache.RemoteCache, "github.com/grafana/grafana/pkg/services/provisioning".ProvisioningService, "github.com/grafana/grafana/pkg/services/login".Service, "github.com/grafana/grafana/pkg/login".Authenticator, accesscontrol.AccessControl, *datasourceproxy.DataSourceProxyService, *"github.com/grafana/grafana/pkg/services/search".SearchService, *"github.com/grafana/grafana/pkg/services/live".GrafanaLive, *pushhttp.Gateway, *plugincontext.Provider, *contexthandler.ContextHandler, *featuremgmt.FeatureManager, *ngalert.AlertNG, librarypanels.Service, libraryelements.Service, quota.Service, social.Service, tracing.Tracer, "github.com/grafana/grafana/pkg/services/export".ExportService, encryption.Internal, *updatechecker.GrafanaService, *updatechecker.PluginsService, searchusers.Service, "github.com/grafana/grafana/pkg/services/datasources".DataSourceService, secrets.Service, *query.Service, "github.com/grafana/grafana/pkg/services/ldap".Groups, teamguardian.TeamGuardian, serviceaccounts.Service, "github.com/grafana/grafana/pkg/services/login".AuthInfoService, "github.com/grafana/grafana/pkg/services/store".HTTPStorageService, *notifications.NotificationService, "github.com/grafana/grafana/pkg/services/dashboards".DashboardService, "github.com/grafana/grafana/pkg/services/dashboards".DashboardProvisioningService, "github.com/grafana/grafana/pkg/services/dashboards".FolderService, permissions.DatasourcePermissionsService, *alerting.AlertNotificationService, dashboardsnapshots.Service, *comments.Service, *"github.com/grafana/grafana/pkg/services/pluginsettings/service".Service, *avatar.AvatarCacheServer, pref.Service, "github.com/grafana/grafana/pkg/services/store".EntityEventsService, accesscontrol.TeamPermissionsService, accesscontrol.FolderPermissionsService, accesscontrol.DashboardPermissionsService, dashver.Service, star.Service, csrf.Service, *"github.com/grafana/grafana/pkg/framework/coremodel/registry".Generic, *"github.com/grafana/grafana/pkg/framework/coremodel/registry".Static, playlist.Service, "github.com/grafana/grafana/pkg/infra/kvstore".KVStore, secrets.Migrator, "github.com/grafana/grafana/pkg/services/secrets/kvstore".UseRemoteSecretsPluginCheck, *"github.com/grafana/grafana/pkg/services/publicdashboards/api".Api, user.Service)
```

</details>

**Environment**:
- Grafana version: 97eec9c2209b0134dcce44c953b8091dcae2a8a3
- OS Grafana is installed on: latest macos

### PR DESCRIPTION
**Pull request by leandro-deveikis**
**What this PR does / why we need it**:
Fixes an error on swagger meta that prevented specs generation

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/53708

**Special notes for your reviewer**:
This fix can be tested with a fresh checkout repo, executing `make all`. On previous versions would throw this error

```
$make build-go
(re)installing /Users/user/Work/go/bin/swagger-v0.29.0
SWAGGER_GENERATE_EXTENSION=false /Users/user/Work/go/bin/swagger-v0.29.0 generate spec -m -w pkg/server -o public/api-spec.json \
	-x "github.com/grafana/grafana/pkg/services/ngalert/api/tooling/definitions" \
	-x "github.com/prometheus/alertmanager" \
	-i pkg/api/swagger_tags.json
json: cannot unmarshal string into Go value of type spec.SecuritySchemeProps
make: *** [public/api-spec.json] Error 1 
```

But after the fix, it can be generated without a problem.

### CODE REVIEW

**Review by kminehart — APPROVED** [review]

**Comment by kminehart** [comment]
Thanks so much!
