### PR TITLE
TablePanel: fix annotations display

### LINKED ISSUE #17639: Annotation table broken since v6.2.x
**What happened**:

After updating from 6.1.6 to 6.2.4, annotation table panels do not load. Instead, they return this error:
`e.data.map is not a function`

See https://community.grafana.com/t/internal-grafana-annotations-no-longer-work-in-a-table/18129 for details.

**What you expected to happen**:

The table should load and display Grafana annotations as table

**How to reproduce it (as minimally and precisely as possible)**:

See https://community.grafana.com/t/internal-grafana-annotations-no-longer-work-in-a-table/18129

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: Grafana
- OS Grafana is installed on: Official Grafana docker image
- User OS & Browser: Ubuntu 18.04 - Firefox 67.0.2 - Chrome  75.0.3770.90 
- Grafana plugins: none
- Others:

### PR DESCRIPTION
**Pull request by ryantxu**
Fixes #17639 

This was caused by the new query runner.  The table panel skips the query runner when the transformation is set to 'annotations'

### CODE REVIEW

**Comment by ryantxu** [comment]
I have no idea how to get a jest test setup for this -- I think it is more worthwhile to put effort into the new react table panel :)

**Comment by ryantxu** [comment]
@marefr -- how should this be tagged so it gets noticed as a bug fix?  and maybe considered for cherry pick?

**Comment by torkelo** [comment]
Add it to 6.2.5 milestone and add label cherry pick needed then it will be included in next patch

**Review by torkelo — APPROVED** [review]
