### PR TITLE
Unified Storage: Adds azure vector embedder and settings for unified storage

### PR DESCRIPTION
**Pull request by owensmallwood**
Adds an azure/openai embedder implementation and config. Test locally with the local integration test and it seems to work 👍

### CODE REVIEW

File: pkg/storage/unified/search/embed/embedder/azure/client.go [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+	"fmt"
+	"io"
+	"net/http"
+	"sort"
+	"strings"
+)
+
+// Doer is the subset of *http.Client we use; declaring it as an interface
+// keeps the client testable without a live Azure endpoint.
+type Doer interface {
```
Comment (owensmallwood) [inline pkg/storage/unified/search/embed/embedder/azure/client.go]: lol what an interface

File: pkg/storage/unified/search/embed/embedder/azure/client.go [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+	reqBody := embedRequest{Input: texts, EncodingFormat: "float"}
+	if dimensions > 0 {
+		reqBody.Dimensions = dimensions
+	}
+	body, err := json.Marshal(reqBody)
+	if err != nil {
+		return EmbedResult{}, fmt.Errorf("azure: marshal embed request: %w", err)
+	}
+
+	url := fmt.Sprintf("%s/openai/deployments/%s/embeddings?api-version=%s", c.endpoint, c.deployment, c.apiVersion)
```
Comment (RafaelPaulovic) [inline pkg/storage/unified/search/embed/embedder/azure/client.go]: Should we use the OpenAI SDK? "github.com/openai/openai-go/v3"

Comment (owensmallwood) [reply pkg/storage/unified/search/embed/embedder/azure/client.go]: yeah I guess it makes the client a little smaller. Will switch to that 👍

**Review by filewalkwithme — DISMISSED** [review]
LGTM

**Comment by RafaelPaulovic** [comment]
The enterprise CI failure (`undefined: SearchSupport` / `undefined: InitializeDocumentBuilders`) was a cross-repo ordering artifact: this branch predates https://github.com/grafana/grafana/pull/126153, which renamed those wire injectors, and the matching enterprise change merged at the same time — so the enterprise build mixed the new generated wire file with the old OSS tree. I've updated the branch with latest main, which contains the new injectors; CI should be green on re-run.

**Review by filewalkwithme — APPROVED** [review]
LGTM
