### ISSUE TITLE
Node graph: if queried from Tempo, does not work in dashboards

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#68440]
### 
# What went wrong?

**What happened**:
Using Node Graph panel with Tempo data source service map query does not work in dashobards.  `value.replace is not a function` error. 
Works in explore.

**What did you expect to happen**:
Node Graph panel with Tempo data soruce service map query in dashboards should work the same as in explore;

  - 

### 
# How do we reproduce it?

1. Have service graph metrics
2. Create dashbaord with "node graph" panel and "Tempo" data soruce with "serviceMap" query
3. It doesn't work

For example
https://otlpcortexdev01.grafana-dev.net/d/b8ed55fc-03c6-4cf8-809d-c3455737be68/node-graph-bug?orgId=1

### 
# What Grafana version are you using?

10.1.x

### 
### Grafana Platform?

A downloaded binary

### Is this a Regression?

Yes

### Are Datasources involved?

Tempo, Prometheus

### Anything else to add?

Seems to have broken after https://github.com/grafana/grafana/pull/66301.  Investigation shows that different result is returned when queried fron explore vs queried from dashboards, and https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/tempo/datasource.ts#L600 assume explore version of response.
