### ISSUE TITLE
Annotation table broken since v6.2.x

### ISSUE THREAD

**Issue by ldormoy** [grafana/grafana#17639]
**What happened**:

After updating from 6.1.6 to 6.2.4, annotation table panels do not load. Instead, they return this error:
`e.data.map is not a function`

See https://community.grafana.com/t/internal-grafana-annotations-no-longer-work-in-a-table/18129 for details.

**What you expected to happen**:

The table should load and display Grafana annotations as table

**How to reproduce it (as minimally and precisely as possible)**:

See https://community.grafana.com/t/internal-grafana-annotations-no-longer-work-in-a-table/18129

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: Grafana
- OS Grafana is installed on: Official Grafana docker image
- User OS & Browser: Ubuntu 18.04 - Firefox 67.0.2 - Chrome  75.0.3770.90 
- Grafana plugins: none
- Others:

**Comment by DmitryShaburov** [comment]
Still same error, Grafana v6.2.5 (6082d19)

**Comment by marefr** [comment]
@ryantxu can you verify/look into this?

**Comment by calebcall** [comment]
Confirmed I'm also still getting the same issue.

**Comment by ryantxu** [comment]
I think I fixed it in #17785 -- main issue is that we changed the query path/structure in 6.3 and the previous patch fixes things for 6.3

You can try:
https://circleci.com/gh/grafana/grafana/116497#artifacts/containers/0

to see if the patch works for you

**Comment by ryantxu** [comment]
please reopen if it is not actually fixed

**Comment by genuss** [comment]
It works!
