### PR TITLE
@grafana/ui: fixes missing getAvailableIcons export

### LINKED ISSUE #106006: Product Area: getAvailableIcons is not a function in 12.1.0
### What happened?

When using the `getAvailableIcons` function from `@grafana/ui` in Grafana version 12.1, it results in an error that completely breaks the plugin.

Environment:

Grafana Version: 12.1
Deployment: Docker image

Image

### What did you expect to happen?

The getAvailableIcons function should work without causing errors or breaking the plugin.

### Did this work before?

Yes
It works fine in 12.0

### How do we reproduce it?

Steps to Reproduce:

Use getAvailableIcons from @grafana/ui in a plugin.
Run the plugin in Grafana 12.1 via Docker image.
Observe the error and plugin failure.

### Is the bug inside a dashboard panel?

_No response_

### Environment (with versions)?

Grafana: 12.1.0

### Grafana platform?

Docker

### Datasource(s)?

_No response_

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What is this feature?**

This commit 9bda7b92938f5b4e6d2ded2c1a4fe59c60e645ff broke the export of `getAvailableIcons`. This PR makes sure we specifically export `getAvailableIcons` for now until we've figured out the root cause.

**Why do we need this feature?**

So `getAvailableIcons` is exported from `@grafana/ui` and not treeshaken

**Who is this feature for?**

Everyone using `getAvailableIcons` function from `@grafana/ui`

**Which issue(s) does this PR fix?**:

Fixes #106006

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

### CODE REVIEW

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Review by academo — APPROVED** [review]

**Review by tomglenn — APPROVED** [review]
Thanks @hugohaggmark!
