### ISSUE TITLE
Following upgrade from 7.3.7 to 7.4.2 - adhoc filter values stored as integer cause e.replace error

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#31335]
**What happened**:
Upgrade from 7.3.7 to 7.4.2, dashboard will not load properly, instead receive e.replace error
**What you expected to happen**:
Dashboard to load as under 7.3.7

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard in 7.3.7.  Add Elasticsearch Data Source.  Add a Table Panel to view the data.  Add an adhoc filter, using a key/ value where the value is a number.  Save the dashboard, and select the option "Save current variable values as dashboard default". You can now go into the dashboard settings and view the JSON to see similar to the snippet below, the value will be stored as an integers (unquoted number). Upgrade to 7.4.2.  Attempt to open dashboard - e.replace error :-)

**Anything else we need to know?**:
I already spent a few hours diff-ing the cause.

In 7.3.7, here is the JSON snippet of the Dashboard.  note the "filters" key, and the value, stored as a JSON Integer (4728):

```
{
          "datasource": "$datasource",
          "error": null,
          "filters": [
            {
              "condition": "",
              "key": "winlog.event_id",
              "operator": "=",
              "value": 4728
            }
          ],
          "hide": 0,
          "label": null,
          "name": "Filters",
          "skipUrlSync": false,
          "type": "adhoc"
        }
```

If upgraded to 7.4.2, the result is the "e.replace" error message.  If you create a new dashboard in 7.4.2, I found the value is stored as a string instead:

```
{
        "datasource": "$datasource",
        "description": null,
        "error": null,
        "filters": [
          {
            "condition": "",
            "key": "winlog.event_id",
            "operator": "=",
            "value": "4728"
          }
        ],
        "hide": 0,
        "label": null,
        "name": "Filters",
        "skipUrlSync": false,
        "type": "adhoc"
      }
```

Probably related to code changes with the adhoc filters (I see some related to regex).

**Environment**:
- Grafana version: 7.4.2 (from 7.3.7, which was working)
- Data source type & version: Elasticsearch 7.9.2
- OS Grafana is installed on: Centos 7
- User OS & Browser: MacOS - Safari and Chrome
- Grafana plugins: Elasticsearch Datasource, Table Plugin
- Others:

**Comment by dprokop** [comment]
Think I've managed to reproduce this with the following dashboard JSON. Import this dashboard, add panel, go to edit mode and it breaks:
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 285,
  "iteration": 1613744900614,
  "links": [],
  "panels": [],
  "schemaVersion": 27,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "datasource": "$datasource",
        "description": null,
        "error": null,
        "filters": [
          {
            "condition": "",
            "key": "winlog.event_id",
            "operator": "=",
            "value": 4728
          }
        ],
        "hide": 0,
        "label": "Filters",
        "name": "Filters",
        "skipUrlSync": false,
        "type": "adhoc"
      },
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "testDS",
          "value": "testDS"
        },
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": "datasource",
        "multi": false,
        "name": "datasource",
        "options": [
          {
            "selected": true,
            "text": "testDS",
            "value": "testDS"
          }
        ],
        "query": "testDS",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "31335",
  "uid": "3tUqiRsGz",
  "version": 8
}
```

Stacktrace:

```
Uncaught TypeError: value.replace is not a function
    at escapeDelimiter (urlParser.ts:20)
    at Array.map (<anonymous>)
    at urlParser.ts:6
    at Array.map (<anonymous>)
    at Module.toUrl (urlParser.ts:6)
    at Object.getValueForUrl (adapter.ts:36)
    at getAllVariableValuesForUrl (getAllVariableValuesForUrl.ts:22)
    at PanelModel.replaceVariables (PanelModel.ts:493)
    at PanelHeader (PanelHeader.tsx:31)
    at PanelHeader (react-hot-loader.development.js:757)
```

**Comment by hugohaggmark** [comment]
Git bisect tells that this was introduced by https://github.com/grafana/grafana/pull/29757, looking into why.

**Comment by hugohaggmark** [comment]
Same issue occurs when Sharing a Dashboard in Grafana 7.3.7. So this might be an ancient issue, looking into how filters end up being stored as numbers.

**Comment by dprokop** [comment]
Thank you @hugohaggmark !
