### ISSUE TITLE
Expression MATH not working 8.5.1 

### ISSUE THREAD

**Issue by thechris1992** [grafana/grafana#48456]
![AC700DF7-1686-4FF2-8B9C-AD6F3469585C](https://user-images.githubusercontent.com/17517167/165816311-af714e76-132b-42cb-8f1a-5d4d9313e0d1.jpeg)

**What happened**:
If i delete all math expressions like $A * 0.35 or $A - $B etc. The Query works. 
with any Expressions Math i got „No Data“. 

Error message on the !:
undefined is not a function (near '...e.replace...')

(I just use ${query}, +, - and * in Math Expressions)

Screen Shows the Playground with 8.5.0 i use the 8.5.1

**What you expected to happen**:
Expressions Math works and Shows the correct value (Power Use kWh * 0.35 Cent)

**How to reproduce it (as minimally and precisely as possible)**:
2 Querys and a Math Operation (Screenshot)

**Anything else we need to know?**:
Works in 8.4.7 the Most time. Expressions with Expression doesn‘t Work the whole time.

After downgrade from 8.5.1 to 8.4.7 it works again. 

**Environment**:
- Grafana version: 8.5.1
- Data source type & version: InfluxDB, 1.8
- OS Grafana is installed on: Raspberry (Debian Light - 5.10.103-v7+ 1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l)
- User OS & Browser: iOS, Google Chrome
- Grafana plugins: - 
- Others: -

**Comment by zoltanbedi** [comment]
I couldn't reproduce this nor on play neither locally running main grafana. I'm going to close this, let me know if you figure out how to reproduce this.
![Screenshot 2022-05-02 at 14 23 01](https://user-images.githubusercontent.com/13729989/166232890-434f288c-14d1-4e7c-b13b-b78e7d22300f.png)

**Comment by zoltanbedi** [comment]
@thechris1992 Please give me a dashboard where I can reproduce this. I tried this with only one data and it is still working.

**Comment by thechris1992** [comment]
```
{
  "id": 13,
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 8
  },
  "type": "stat",
  "title": "Panel Title",
  "targets": [
    {
      "refId": "A",
      "datasource": {
        "type": "influxdb",
        "uid": "000000002"
      },
      "policy": "bar",
      "resultFormat": "time_series",
      "orderByTime": "ASC",
      "tags": [],
      "groupBy": [],
      "select": [
        [
          {
            "type": "field",
            "params": [
              "value"
            ]
          },
          {
            "type": "last",
            "params": []
          }
        ]
      ],
      "measurement": "payment.ended"
    },
    {
      "refId": "B",
      "datasource": {
        "type": "influxdb",
        "uid": "000000002"
      },
      "policy": "bar",
      "resultFormat": "time_series",
      "orderByTime": "ASC",
      "tags": [],
      "groupBy": [],
      "select": [
        [
          {
            "type": "field",
            "params": [
              "value"
            ]
          },
          {
            "type": "first",
            "params": []
          }
        ]
      ],
      "measurement": "payment.started",
      "hide": false
    },
    {
      "refId": "C",
      "type": "math",
      "datasource": {
        "type": "__expr__",
        "uid": "__expr__"
      },
      "hide": false,
      "expression": "$A * 0.35\n"
    },
    {
      "refId": "D",
      "type": "math",
      "datasource": {
        "type": "__expr__",
        "uid": "__expr__"
      },
      "hide": false,
      "expression": "$B * 0.35"
    },
    {
      "refId": "E",
      "type": "math",
      "datasource": {
        "type": "__expr__",
        "uid": "__expr__"
      },
      "hide": false,
      "expression": "$C + $B"
    },
    {
      "refId": "F",
      "type": "math",
      "datasource": {
        "type": "__expr__",
        "uid": "__expr__"
      },
      "hide": false,
      "expression": "$A - $B"
    }
  ],
  "fieldConfig": {
    "defaults": {
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": []
  },
  "datasource": {
    "uid": "000000002",
    "type": "influxdb"
  },
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "textMode": "auto",
    "colorMode": "value",
    "graphMode": "area",
    "justifyMode": "auto"
  },
  "pluginVersion": "8.5.0"
}
```
[Grafana Play Home-1651503636412.zip](https://github.com/grafana/grafana/files/8603764/Grafana.Play.Home-1651503636412.zip)


The + and - does not work.
![image](https://user-images.githubusercontent.com/17517167/166256553-ad4f2f10-3b1c-45c6-b2bf-3ffc332eff0a.png)

**Comment by zoltanbedi** [comment]
Hi @thechris1992,
I'm sorry but I'm still unable to replicate this with the test datasource see.
![Screenshot 2022-05-03 at 12 18 00](https://user-images.githubusercontent.com/13729989/166437344-704a7c7d-686b-442c-ad9d-7ce163b562ea.png)

```json
{
  "annotations": {
    "enable": false,
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 2,
  "links": [
    {
      "icon": "external link",
      "tags": [],
      "targetBlank": true,
      "title": "Learn more at Grafana.com",
      "tooltip": "",
      "type": "link",
      "url": "https://grafana.com?pg=play&plcmt=home"
    },
    {
      "icon": "cloud",
      "tags": [],
      "targetBlank": true,
      "title": "Grafana Cloud now free with 50gb logs, 10K metric series",
      "tooltip": "",
      "type": "link",
      "url": "https://grafana.com/signup/cloud/connect-account?pg=play&plcmt=home"
    }
  ],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "NwohV7lnk"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 13,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "textMode": "auto"
      },
      "pluginVersion": "8.5.1",
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "NwohV7lnk"
          },
          "refId": "A",
          "scenarioId": "random_walk"
        },
        {
          "datasource": {
            "type": "testdata",
            "uid": "NwohV7lnk"
          },
          "refId": "B",
          "scenarioId": "random_walk"
        },
        {
          "datasource": {
            "type": "__expr__",
            "uid": "__expr__"
          },
          "expression": "$A * 0.35\n",
          "hide": false,
          "refId": "C",
          "type": "math"
        },
        {
          "datasource": {
            "type": "__expr__",
            "uid": "__expr__"
          },
          "expression": "$B * 0.35",
          "hide": false,
          "refId": "D",
          "type": "math"
        },
        {
          "datasource": {
            "type": "__expr__",
            "uid": "__expr__"
          },
          "expression": "$C + $B",
          "hide": false,
          "refId": "E",
          "type": "math"
        },
        {
          "datasource": {
            "type": "__expr__",
            "uid": "__expr__"
          },
          "expression": "$A - $B",
          "hide": false,
          "refId": "F",
          "type": "math"
        }
      ],
      "title": "Panel Title",
      "type": "stat"
    }
  ],
  "refresh": "",
  "schemaVersion": 36,
  "style": "dark",
  "tags": [
    "startpage",
    "home",
    "Home"
  ],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-1h",
    "to": "now"
  },
  "timepicker": {
    "collapse": false,
    "enable": true,
    "notice": false,
    "now": true,
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "status": "Stable",
    "time_options": [
      "5m",
      "15m",
      "1h",
      "2h",
      " 6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ],
    "type": "timepicker"
  },
  "timezone": "browser",
  "title": "Grafana Play Home",
  "uid": "000000012",
  "version": 3,
  "weekStart": ""
}
```

**Comment by thechris1992** [comment]
@zoltanbedi and if you use my dashboard with influxdb?

**Comment by thechris1992** [comment]
please test it with my Dashboard not with oder Settings… @zoltanbedi

**Comment by zoltanbedi** [comment]
Hey @thechris1992,
I was able to reproduce this with this dashboard. Thanks for bearing with me.
```json
{
  "annotations": {
    "enable": false,
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 280,
  "links": [
    {
      "icon": "external link",
      "tags": [],
      "targetBlank": true,
      "title": "Learn more at Grafana.com",
      "tooltip": "",
      "type": "link",
      "url": "https://grafana.com?pg=play&plcmt=home"
    },
    {
      "icon": "cloud",
      "tags": [],
      "targetBlank": true,
      "title": "Grafana Cloud now free with 50gb logs, 10K metric series",
      "tooltip": "",
      "type": "link",
      "url": "https://grafana.com/signup/cloud/connect-account?pg=play&plcmt=home"
    }
  ],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "influxdb",
        "uid": "P15396BDD62B2BE29"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 13,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "textMode": "auto"
      },
      "pluginVersion": "9.0.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "P15396BDD62B2BE29"
          },
          "groupBy": [],
          "measurement": "cpu",
          "orderByTime": "ASC",
          "policy": "default",
          "query": "SELECT last(\"value\") FROM \"autogen\".\"logins.count\" WHERE $timeFilter",
          "rawQuery": false,
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "first"
              }
            ]
          ],
          "tags": []
        },
        {
          "datasource": {
            "type": "influxdb",
            "uid": "P15396BDD62B2BE29"
          },
          "groupBy": [],
          "hide": false,
          "measurement": "cpu",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "B",
          "resultFormat": "table",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "last"
              }
            ]
          ],
          "tags": []
        },
        {
          "datasource": {
            "name": "Expression",
            "type": "__expr__",
            "uid": "__expr__"
          },
          "expression": "$A - $B",
          "hide": false,
          "refId": "F",
          "type": "math"
        }
      ],
      "title": "Panel Title",
      "type": "stat"
    }
  ],
  "refresh": "",
  "schemaVersion": 36,
  "style": "dark",
  "tags": [
    "startpage",
    "home",
    "Home"
  ],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-5m",
    "to": "now"
  },
  "timepicker": {
    "collapse": false,
    "enable": true,
    "notice": false,
    "now": true,
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "status": "Stable",
    "time_options": [
      "5m",
      "15m",
      "1h",
      "2h",
      " 6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ],
    "type": "timepicker"
  },
  "timezone": "browser",
  "title": "Grafana Play Home",
  "uid": "000000012",
  "version": 12,
  "weekStart": ""
}
```

**Comment by thechris1992** [comment]
Still with v8.5.3 - so no „side effects“

**Comment by thechris1992** [comment]
:(

**Comment by thechris1992** [comment]
@zoltanbedi

**Comment by itsmylife** [comment]
@thechris1992 I went over the issue and found the problem. I am copying the following straight from [the docs](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/expression-queries/#operations): 

> If both $A and $B are time series data, then the operation between each value in the two series is performed for each time stamp that exists in both $A and $B. The Resample operation can be used to line up time stamps. (Note: in the future, we plan to add options to the Math operation for different behaviors).

See the image below:

![Image](https://user-images.githubusercontent.com/820946/229195826-e565a27a-5c7d-4774-8185-aece982fc994.png)


As you can see the timestamps are not lining up. For a workaround you can  use `resample` operation or simply `reduce` one of the queries. So `$influxAReduced + $InfluxB` works. 

(Note: in the future, we plan to add options to the Math operation for different behaviors).


cc: @kylebrandt

**Comment by itsmylife** [comment]
I am closing this issue. Feel free to open a new issue if you need it.
