### ISSUE TITLE
Dashboards: ad-hoc filter for a numeric field causes a page error

### ISSUE THREAD

**Issue by cartw** [grafana/grafana#99021]
### What happened?

Found on grafana 11.3.1. 
I am using adhoc filters against an opensearch database. 
When I try and use a query such as greater than or even = against a numeric field, as soon as I try and enter the  value I want the dashboard displays an unexpected error.

https://github.com/user-attachments/assets/9d128d82-15f7-43ca-aca5-ae9aa6346a20

as per #96915 - if I set "dashboardScene = false" in feature toggles the adhoc filters go back to working as expected so this seems to be another case of Scene not supporting adhoc filter.  

### What did you expect to happen?

The behaviour before, and reproducible with Scene disabled is that I can type in the value field, no crash occurs and I am able to filter my data for values exceeding my desired threshold. 

### Did this work before?

I think it worked in 11.2. It certainly worked in 10.x and as stated disabling dashboardScene shows the correct behaviour.  

### How do we reproduce it?

See above

### Environment (with versions)?

Grafana: 11.3.1
OS: MacOS
Browser:  firefox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by haelekuin** [comment]
What version of the Opensearch datasource plugin are you using? Using 2.22.2 and 2.22.3 I can't replicate the issue on Grafana 11.3.1. https://grafana.com/grafana/plugins/grafana-opensearch-datasource/?tab=changelog.

**Comment by cartw** [comment]
Apparently 2.17.4 ... 

OK I'll try updating it and see what happens.

**Comment by cartw** [comment]
No,  I updated to 2.22.3 

<img width="554" alt="Image" src="https://github.com/user-attachments/assets/933d514e-ac8c-49b3-a238-f28c135080b5" />

set dashboardScene = true in feature toggles, restarted grafana and I can reproduce the same page crash. AS soon as I type in the value box I get the `TypeError: Je.match is not a function` stack trace

**Comment by cartw** [comment]
I've also just tested with an elasticsearch datasource and the exact same thing happens.

**Comment by cartw** [comment]
I can also reproduce it on https://play.grafana.org/d/play-elastic-web-logs/elasticsearch-83a-web-logs?orgId=1&from=1998-04-30T20:00:18.000Z&to=1998-04-30T20:10:33.000Z&timezone=utc 
by adding an adhoc filter and then trying to filter the size field 

https://github.com/user-attachments/assets/38cc0623-177c-4b0f-a932-c3f11f88c313

Note in case it's not clear,  I'm not selecting a value from the drop down, I'm trying to type a value into the box. As soon as I press a key, the page error occurs.

**Comment by kevinwcyu** [comment]
@grafana/dashboards-squad, is there a known issue with scenes and ad-hoc filters? I'm going to remove this from our team's board for now since it affects multiple data sources with scenes enabled. Please add it back to our board if this is something that we need to update in the data sources though.

**Comment by Sergej-Vlasov** [comment]
@kevinwcyu  thank you for the ping. Indeed I identified there is an error with the search mechanism. Working on the fix right now.

You can have a workaround for this issue by selecting values with a mouse instead of narrowing down results with search string or disabling `dashboardScene` feature toggle

**Comment by Sergej-Vlasov** [comment]
@kevinwcyu on further investigation I found why the search is breaking. `getTagValues` should return the type `MetricFindValue[]` which is:
```typescript
export interface MetricFindValue {
  text: string;
  value?: string | number;
  group?: string;
  expandable?: boolean;
}
```
The error originates from the field `text` which actually comes through as a `number`. Here is example with elastic search:

getTagKeys response (where `bucket.key` is `number`):
<img width="456" alt="Image" src="https://github.com/user-attachments/assets/8251dc5f-65b9-460c-9f26-d89589368e63" />

[code](https://github.com/grafana/grafana/blob/c1eac9f9973fb5640013f10cb733eae6bfe1fff7/public/app/plugins/datasource/elasticsearch/datasource.ts#L896) that parses that (and assumes it is always a string):

<img width="659" alt="Image" src="https://github.com/user-attachments/assets/2ba90ec0-0db9-46f5-9df9-8dda8e2f6203" />

And thus `text` comes through as a `number` instead of string because `bucket.key` is a number.

I reckon its better to fix this from the datasources side because the response differs from type. We could just adjust this in scenes but this could cause more runtime errors in other parts. Let me know if you agree/disagree.

**Comment by cartw** [comment]
> You can have a workaround for this issue by selecting values with a mouse


That's really not a practical suggestion for a numeric field where there can be an almost infinite number of values. Especially since the drop down only shows the first 500 values. So if I want to filter on requests that took longer than a thousand milliseconds I can only scroll from 0 as far as 499. I can select that and then, it turns out, edit the URL to change teh value to what I want... but c'mon.

**Comment by Sergej-Vlasov** [comment]
@cartw this was just a suggestion on how to avoid an error until we fix it.

Addressed from scenes to stop the bleed in the mean time https://github.com/grafana/scenes/pull/1029

**Comment by kevinwcyu** [comment]
Thanks @Sergej-Vlasov. We can make the change on the data source side to fix up our types and return values that match the `MetricFindValue` type. I'll move this over to our board and remove it from your board.
