### PR TITLE
Tempo: Fix get label values based on CoreApp type

### LINKED ISSUE #68440: Node graph: if queried from Tempo, does not work in dashboards
### 
# What went wrong?

**What happened**:
Using Node Graph panel with Tempo data source service map query does not work in dashobards.  `value.replace is not a function` error. 
Works in explore.

**What did you expect to happen**:
Node Graph panel with Tempo data soruce service map query in dashboards should work the same as in explore;

  - 

### 
# How do we reproduce it?

1. Have service graph metrics
2. Create dashbaord with "node graph" panel and "Tempo" data soruce with "serviceMap" query
3. It doesn't work

For example
https://otlpcortexdev01.grafana-dev.net/d/b8ed55fc-03c6-4cf8-809d-c3455737be68/node-graph-bug?orgId=1

### 
# What Grafana version are you using?

10.1.x

### 
### Is the bug inside a Dashboard Panel?

_No response_

### Grafana Platform?

A downloaded binary

### User's OS?

_No response_

### User's Browser?

_No response_

### Is this a Regression?

Yes

### Are Datasources involved?

Tempo, Prometheus

### Anything else to add?

Seems to have broken after https://github.com/grafana/grafana/pull/66301.  Investigation shows that different result is returned when queried fron explore vs queried from dashboards, and https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/tempo/datasource.ts#L600 assume explore version of response.

### PR DESCRIPTION
**Pull request by joey-grafana**
**What is this feature?**

Fixes an issue where we were incorrectly getting the label values for `errorAndDurationQuery` for explore only, not considering that queries may also come from non-explore.

**Why do we need this feature?**

To fix regex bug where values are not string in `getEscapedSpanNames` by getting proper span names.

**Who is this feature for?**

Tempo users.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/68440

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

### CODE REVIEW

**Review by domasx2 — APPROVED** [review]
tested locally, works :+1:

File: public/app/plugins/datasource/tempo/datasource.ts [hunk 1]
```diff
@@ -597,7 +599,20 @@ function errorAndDurationQuery(
   let serviceGraphViewMetrics = [];
   let errorRateBySpanName = '';
   let durationsBySpanName: string[] = [];
-  const spanNames = getEscapedSpanNames(rateResponse.data[0][0]?.fields[1]?.values ?? []);
+
+  let labels = [];
+  if (request.app === CoreApp.Explore) {
+    if (rateResponse.data[0][0]?.fields[1]?.values) {
```
Comment (aocenas) [inline public/app/plugins/datasource/tempo/datasource.ts:605]: Why is the response different for explore vs dashboard?

File: public/app/plugins/datasource/tempo/datasource.ts [hunk 2]
```diff
@@ -597,7 +599,20 @@ function errorAndDurationQuery(
...
+      labels = rateResponse.data[0][0]?.fields[1]?.values;
+    }
+  } else if (rateResponse.data[0]) {
+    rateResponse.data[0].map((df: DataFrame) => {
```
Comment (aocenas) [inline public/app/plugins/datasource/tempo/datasource.ts:609]: If you are not returning anything from `map` I think it would be better to use `forEach` to be clear it has a side effect.

File: public/app/plugins/datasource/tempo/datasource.ts [hunk 3]
```diff
@@ -597,7 +599,20 @@ function errorAndDurationQuery(
...
+      if (df.fields[1]?.labels && df.fields[1]?.labels['span_name']) {
+        labels.push(df.fields[1]?.labels['span_name']);
```
Comment (aocenas) [inline public/app/plugins/datasource/tempo/datasource.ts:611]: Do I get this right that we have a dataFrame per span?

File: public/app/plugins/datasource/tempo/datasource.ts (hunk 1 above)
Comment (joey-grafana) [reply public/app/plugins/datasource/tempo/datasource.ts:605]: It seems that in dashboards there's multiple data frames returned, each with span_name label. In explore some sort of transform is applied and all are aggregated into a single data frame, with span_name field and span names as values

File: public/app/plugins/datasource/tempo/datasource.ts (hunk 3 above)
Comment (joey-grafana) [reply public/app/plugins/datasource/tempo/datasource.ts:611]: Outside of explore, yes.

File: public/app/plugins/datasource/tempo/datasource.ts (hunk 1 above)
Comment (aocenas) [reply public/app/plugins/datasource/tempo/datasource.ts:605]: Interesting, do you know why is that? I know we have different formats for time series, with either the wide format or dataFrame per series but for trace, to have a dataFrame per span seems a bit inefficient (especially if we have traces with thousands of spans)

Comment (aocenas) [reply public/app/plugins/datasource/tempo/datasource.ts:605]: oh right, this is actually a prometheus query that returns the nodegraph data so I assume this is exactly the case that prometheus returns a different shape. In that case span_name is basically a node name and so we probably don't really have that many nodes? I mean maybe the naming is weird, would expect the label to be `service_name` probably not `span_name` as there can be more spans per single service but we want to show just the service in the service map

Comment (joey-grafana) [reply public/app/plugins/datasource/tempo/datasource.ts:605]: That's basically it. I don't think we can have that many nodes really and have not seen a case where we do. Agreed the naming is a bit weird but for now I think it's ok. Not exactly sure where we would change the `span_name` or if it's in the Tempo metrics generator/Prometheus code, honestly it's probably not necessary right now.
