### ISSUE TITLE
Adding links to panel causes error

### ISSUE THREAD

**Issue by paulpet** [grafana/grafana#25464]
**What happened**:
Adding a link to any panel type, then saving and returning to the dashboard will return a javascript error as soon as I move the mouse cursor over the link icon in the corner of the panel.

The error returned is:
```
TypeError: e.replace is not a function. (In 'e.replace(/\|/g,"__gfp__")', 'e.replace' is undefined)
    in t
    in P
    in div
    in t
    in t
    in t
    in t
    in t
    in f
    in t
    in div
    in t
    in div
    in t
    in x
    in div
    in t
    in div
    in t
    in x
    in div
    in o
    in DraggableCore
    in t
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Just need to add a link.

**Anything else we need to know?**:
This was originally a v6 grafana set up and link worked fine then. Since upgrading to v7 it's been broken including 7.0.0 & 7.0.1 (i think).

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Any
- OS Grafana is installed on: Centos7
- User OS & Browser: macOS using Safari or Brave Browser
- Grafana plugins:
installed plugins:
briangann-datatable-panel @ 1.0.1
grafana-piechart-panel @ 1.5.0
grafana-polystat-panel @ 1.2.0
grafana-sensu-app @ 1.0.6
briangann-sensu-datasource @ 0.0.1
grafana-worldmap-panel @ 0.3.2
mtanda-heatmap-epoch-panel @ 0.1.7
neocat-cal-heatmap-panel @ 0.0.3
savantly-heatmap-panel @ 0.2.0
sensu-sensugo-datasource @ 1.0.3
vonage-status-panel @ 1.0.9
xginn8-pagerduty-datasource @ 0.2.1
- Others:

**Comment by AgnesToulet** [comment]
Hi, I couldn't reproduce this issue. The error seems related to variables, are you using any variable in your link? Can you provide a broken link configuration and, if you're using variables, the associated variable definition? Thanks.

**Comment by paulpet** [comment]
Hi @AgnesToulet, no it will literally error out with any link. I can add just https://www.google.com and it will error out when I hover over the corner link icon of a panel.

**Comment by torkelo** [comment]
not able to reproduce as well

**Comment by adeverteuil** [comment]
Hi, we have a customer reporting a similar bug. Their panel was build on a previous version of Grafana, maybe v6.2 or earlier. Their links array looks like this:

```
      "links": [
        {
          "dashUri": "db/test-dashboard",
          "dashboard": "Test Dashboard",
          "includeVars": true,
          "keepTime": true,
          "targetBlank": true,
          "title": "Test Dashboard",
          "type": "dashboard"
        }
      ],
```

Modern links look like this:

```

  "links": [
    {
      "url": "https://google.com/",
      "title": "Test"
    }
  ],
```

@paulpet Can you share the dashboard JSON model, preferably with a single panel that triggers the bug? Can you reproduce the bug on a panel that was created on v7.1.1 or is it a dashboard created on a previous version of Grafana?

**Comment by peterholmberg** [comment]
@paulpet are you still having an issue with this using 7.1.3? Please reopen if so
