### ISSUE TITLE
MySQL $__interval_ms doesn't work in 5.4+

### ISSUE THREAD

**Issue by Need1e** [grafana/grafana#14507]
$__interval_ms stoped working since 5.4 

Please include this information:
### What Grafana version are you using?
5.4, 5.4.1, 5.4.2
### What datasource are you using?
MySQL
### What OS are you running grafana on?
Ubuntu 14
### What did you do?
Upgraded to 5.4, 5.4.1, 5.4.2
### What was the expected result?
$__interval_ms should return value

### What happened instead?
- Query inspector shows nothing (updating icon forever)
- charts are not shown
- error "t.replace is not a function" displayed on the charts
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
- no requests / responses in dev tools

**Comment by torkelo** [comment]
what does your query look like?

**Comment by torkelo** [comment]
do you have a panel json to share as well?

**Comment by Need1e** [comment]
Worked flawlessly until 5.4:

SELECT
  (change_time div ($__interval_ms div 330) * ($__interval_ms div 330)) as time_sec,
  avg(device_value) as value,
  "Outdoor" as metric
FROM dev_id_13
WHERE change_time>=$__unixEpochFrom() and change_time<=$__unixEpochTo()
GROUP BY time_sec ASC

[Temperatures - table Copy-1545042880750.zip](https://github.com/grafana/grafana/files/2685656/Temperatures.-.table.Copy-1545042880750.zip)

**Comment by Need1e** [comment]
Yes, sure.

Shared both.

**Comment by yoshar1** [comment]
I can confirm the same problem, also using MySQL as a data source.
This query throws the 't.replace is not a function' error 5.4:
```
SELECT
  UNIX_TIMESTAMP(Updated) as time_sec,
  Avg(Value) as value,
  Name as metric
FROM measurements
INNER JOIN sensors ON sensors.SID = measurements.SID 
WHERE $__timeFilter(Updated) AND measurements.SID = 142
GROUP BY UNIX_TIMESTAMP(Updated) DIV ($__interval_ms/1000)
ORDER BY Updated ASC
```


Whereas this one does not (and works fine in 5.4):
```
SELECT
  UNIX_TIMESTAMP(Updated) as time_sec,
  (Value) as value,
  Name as metric
FROM measurements
INNER JOIN sensors ON sensors.SID = measurements.SID 
WHERE $__timeFilter(Updated) AND measurements.SID = 142
ORDER BY Updated ASC
```

**Comment by marefr** [comment]
Confirmed bug. PR on the way, but this fix may have to wait until patch release after 6.0 stable. We'll see
